### ISSUE TITLE
vtgate/healthcheck: panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#10170]
Was perusing panics today and found this. It has happened 15 times over the last 30 days, running various near tip versions > v13

```go
panic: assignment to entry in nil map

goroutine 616 [running]:
vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).updateHealth(0xc000167440, 0xc001c0f1d0, 0xc001f4aba0, 0x0, 0x0)
	vitess.io/vitess/go/vt/discovery/healthcheck.go:435 +0x499
vitess.io/vitess/go/vt/discovery.(*tabletHealthCheck).checkConn(0xc00091af30, 0xc000167440)
	vitess.io/vitess/go/vt/discovery/tablet_health_check.go:298 +0x479
created by vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).AddTablet
	vitess.io/vitess/go/vt/discovery/healthcheck.go:368 +0x60f
```

**Comment by deepthi** [comment]
Can you give us the SHA you are running? those line numbers don't correspond to what we have on `main`.

**Comment by derekperkins** [comment]
`Version: 14.0.0-SNAPSHOT (Git revision 86a2572719ee59d12526c3fdc09897aed8ed296d branch 'vt_streamed_cols') built on Thu Apr 28 19:57:49 UTC 2022 by root@buildkitsandbox using go1.18.1 linux/amd64`
