### ISSUE TITLE
sqltypes.MakeRowTrusted: panic: runtime error: index out of range [2] with length 2

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#10172]
Was perusing panics today and found this. It has happened 12 times over the last 30 days, running inside the Go driver at v0.12.2

```go
panic: runtime error: index out of range [2] with length 2

goroutine 157 [running]:
vitess.io/vitess/go/sqltypes.MakeRowTrusted(...)
	/Users/derek/go/pkg/mod/vitess.io/vitess@v0.12.2/go/sqltypes/result.go:254
vitess.io/vitess/go/sqltypes.proto3ToRows({0xc00090daa0, 0x2, 0xc0000abb00?}, {0xc0006fd168, 0x1, 0xc000a6bd10?})
	/Users/derek/go/pkg/mod/vitess.io/vitess@v0.12.2/go/sqltypes/proto3.go:92 +0x21b
vitess.io/vitess/go/sqltypes.CustomProto3ToResult({0xc00090daa0?, 0x20?, 0x7f8f058501d8?}, 0xc000cc8380)
	/Users/derek/go/pkg/mod/vitess.io/vitess@v0.12.2/go/sqltypes/proto3.go:135 +0x45
vitess.io/vitess/go/vt/vtgate/grpcvtgateconn.(*streamExecuteAdapter).Recv(0xc000143f00)
	/Users/derek/go/pkg/mod/vitess.io/vitess@v0.12.2/go/vt/vtgate/grpcvtgateconn/conn.go:139 +0x7c
vitess.io/vitess/go/vt/vitessdriver.(*streamingRows).Next(0xc000ac6870, {0xc000597740, 0x2, 0x2})
	/Users/derek/go/pkg/mod/vitess.io/vitess@v0.12.2/go/vt/vitessdriver/streaming_rows.go:76 +0xbb
database/sql.(*Rows).nextLocked(0xc000ac8780)
	/usr/local/Cellar/go/1.18/libexec/src/database/sql/sql.go:3008 +0x111
database/sql.(*Rows).Next.func1()
	/usr/local/Cellar/go/1.18/libexec/src/database/sql/sql.go:2986 +0x2f
database/sql.withLock({0x14d31c8, 0xc000ac87b0}, 0xc00059e778)
	/usr/local/Cellar/go/1.18/libexec/src/database/sql/sql.go:3437 +0x8c
database/sql.(*Rows).Next(0xc000ac8780)
	/usr/local/Cellar/go/1.18/libexec/src/database/sql/sql.go:2985 +0x6f
go.nozzle.io/pkg/workers/vitessmessages.(*SourceQueue).pipeMessages.func1()
	/Users/derek/Code/go.nozzle.io/pkg/workers/vitessmessages/source_queue.go:140 +0x32
created by go.nozzle.io/pkg/workers/vitessmessages.(*SourceQueue).pipeMessages
	/Users/derek/Code/go.nozzle.io/pkg/workers/vitessmessages/source_queue.go:137 +0xf3
```

**Comment by harshit-gangal** [comment]
The code path is very old to see such panic. The information is not enough to reproduce the issue.
@derekperkins could you share more information so that we can try and see the issue?

@vmg do you think it can be related to the protobuf upgrade?

Vitess Version looks like 12.0

**Comment by vmg** [comment]
Not `proto` related. It seems like this could be an issue with the  way we parsed stuff from the upstream MySQL reply, which is making us miss some fields.

**Comment by derekperkins** [comment]
The Go driver is v0.12.2, and over the period, Vitess components were running v12, v13, and tip. This is message related code, running `stream * from msg_tbl`
