### ISSUE TITLE
vtgate: panic on redeployment

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#10782]
looks like this might be a race condition on startup? I've only seen it once, so it's not common nor a major concern for us, just noting in case it is indicative of any deeper issues

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf2021a]

goroutine 1027 [running]:
vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).getKeyspaceUpdateController(0xc000119950, 0x0)
	vitess.io/vitess/go/vt/vtgate/schema/tracker.go:129 +0x9a
vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).Start.func1({0x23defb0, 0xc000a04b40}, 0xc000119950)
	vitess.io/vitess/go/vt/vtgate/schema/tracker.go:113 +0x49
created by vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).Start
	vitess.io/vitess/go/vt/vtgate/schema/tracker.go:109 +0xfb
```

**Comment by yoheimuta** [comment]
I've run into the same panic once, right after the vtgate started shutting down gracefully.

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/1223268/209279330-1837306c-3b9b-4e91-8890-c51295e2bd27.png">

Running `Version: 15.0.1 (Git revision 13ee9c817638d59bebd6bc598f9d673a893c41cd branch 'heads/v15.0.1') built on Tue Nov 29 21:08:39 UTC 2022 by vitess@buildkitsandbox using go1.18.7 linux/amd64.`
