### ISSUE TITLE
Feature Request: Workaround for bug in PHP PDO?

### ISSUE THREAD

**Issue by quinox** [vitessio/vitess#11556]
### Feature Description

Hello good people,

I'd like to about a possible workaround in Vitess for a bug in PHP PDO ([the bug: #9787](https://github.com/php/php-src/issues/9787)).

The short of it: there is a bug in PHP PDO that makes that it so can't parse error packets above a certain size. When that happens PHP ignores the error and then the following query using that connection will always break.

The reason the error packet gets so big is that I'm executing big queries (procedurally generated, inserting a lot of data in 1 query), and it appears that `vtgate` includes the offending query+bindvars in the error message (which is most helpful!), so the bigger my query the bigger the error packet.

To be clear: PHP PDO has no problem executing a big query, and if the DB likes the data everything works as expected. It's only when fe. a datapoint isn't compatible with the database schema (float value out of range, that kind of stuff) that the resulting error message will break PDO.

---

I tried adding `--sql-max-length-errors 10 --vtgate-config-terse-errors --normalize_queries=false --redact-debug-ui-queries` on my `vtgate` and `--sql-max-length-errors 10 --sanitize_log_messages --redact-debug-ui-queries ` on my `vttablet`; this does fix the problem when I use PDO to execute a huge string query, but it doesn't help when I use a prepared statement and binding vars.

Is there a way to limit the error packet size when using bind vars as well?

---

For an in-depth problem description of the PDO bug please see the [PHP issue tracker](https://github.com/php/php-src/issues/9787) but the summary is as follows:

If I execute a small query that can't be stored in the DB everything works as expected:
```
$ php reproduce_truncated_result_header_longtext.php
LOGGING: I'm going to perform this query:
INSERT INTO mychars(val) VALUES ('first'), ('bla  bla  bla '), (NULL)

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 target: vitess_production_clone.0.primary: vttablet: rpc error: code = InvalidArgument desc = Column 'val' cannot be null (errno 1048) (sqlstate 23000) (CallerID: userData1): Sql: "insert into mychars(val) values (:vtg1), (:vtg2), (null)", BindVars: {vtg1: "type:VARCHAR value:\"first\""vtg2: "type:VARCHAR value:\"bla  bla  bla \""} in /root/reproduce_truncated_result_header_longtext.php:27
Stack trace:
#0 /root/reproduce_truncated_result_header_longtext.php(27): PDO->exec('INSERT INTO myc...')
#1 {main}
  thrown in /root/reproduce_truncated_result_header_longtext.php on line 27
```

It goes all sideways when the query itself is big *and* the DB doesn't like my data:
```
$ php reproduce_truncated_result_header_longtext.php
LOGGING: I'm going to perform this query:
INSERT INTO mychars(val) VALUES ('first'), ('bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla  bla '), (NULL)

Warning: PDO::exec(): Error reading result set's header in /root/reproduce_truncated_result_header_longtext.php on line 27

LOGGING: Executing another query:
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute. in /root/reproduce_truncated_result_header_longtext.php:32
Stack trace:
#0 /root/reproduce_truncated_result_header_longtext.php(32): PDO->query('SELECT * FROM m...')
#1 {main}
  thrown in /root/reproduce_truncated_result_header_longtext.php on line 32
```

The unbuffered talk is a red herring, the real issue is that PDO didn't process the first error message properly, decided to basically ignore it (that's the "Warning: PDO::exec()" line) and then it can no longer use the connection.

### Use Case(s)

To be able to see useful errors from Vitess using PHP PDO while the cogs turn slowly on the PHP side to fix the core issue over there.

**Comment by quinox** [comment]
Just a FYI: lowering the query limit all the way to 10 was a bad idea, it will trigger a runtime error when it starts cutting because in  [truncate_query.go:  truncateQuery](https://github.com/vitessio/vitess/blob/8aebb6fdbd6b07024c3df7c14f2edbdf52c9f5dc/go/vt/sqlparser/truncate_query.go#L72) it runs `return comments.Leading + sql[:max-12] + " [TRUNCATED]" + comments.Trailing`, resulting in:

```
E1028 16:12:15.754347 1836408 tabletserver.go:1335] Uncaught panic for Sql: "select x.idSite, x.description, x.site_timezone, x.noDataAlarmTimeout, <rest of query trimmed by me>", BindVars: {}:
runtime error: slice bounds out of range [:-2]
runtime/panic.go:99 (0x433e7e)
vitess.io/vitess/go/vt/sqlparser/truncate_query.go:38 (0xcf4f24)
vitess.io/vitess/go/vt/sqlparser/truncate_query.go:51 (0x1347273)
vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:1427 (0x1347268)
vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:1401 (0x1346e79)
vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:1311 (0x1346134)
vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:724 (0x13413a4)
vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:866 (0x13423a8)
vitess.io/vitess/go/vt/vttablet/grpcqueryservice/server.go:242 (0x141bd58)
vitess.io/vitess/go/vt/proto/queryservice/queryservice_grpc.pb.go:937 (0x140fbcf)
google.golang.org/grpc@v1.45.0/server.go:1282 (0xa2572e)
google.golang.org/grpc@v1.45.0/server.go:1619 (0xa29d5a)
google.golang.org/grpc@v1.45.0/server.go:921 (0xa23297)
runtime/asm_amd64.s:1571 (0x469420)
```

I've increased my cut limit to 20 and now it cuts correctly.
