### ISSUE TITLE
Bug Report: {"level":"panic","ts":"2023-09-25T07:41:12.358351Z","caller":"backend/backend.go:189","msg":"failed to open database","path":"/var/etcd/member/snap/db","error":"no locks"} in onpremis kubernetes , deployed using operator

### ISSUE THREAD

**Issue by Kibria7533** [vitessio/vitess#14087]
### Overview of the Issue

Here are some details about my setup:
I'm running Vitess using the Vitess Operator.
My Kubernetes cluster is hosted on-premises.
I have verified that the Persistent Volume Claim (PVC)  live .
Despite these checks, I'm still encountering the "failed to open database" error, with the mention of "no locks." I've also ensured that there is enough disk space available on the system.
I would greatly appreciate any insights or suggestions from the community regarding this issue. If anyone has encountered a similar problem or has ideas about what might be causing this error, please let me know. Your assistance would be invaluable in helping me resolve this problem and get my Vitess cluster up and running

### Reproduction Steps

"level":"panic","ts":"2023-09-25T08:07:08.960228Z","caller":"backend/backend.go:189","msg":"failed to open database","path":"/var/etcd/member/snap/db","error":"no locks available","stacktrace":"go.etcd.io/etcd/server/v3/mvcc/backend.newBackend\n\tgo.etcd.io/etcd/server/v3/mvcc/backend/backend.go:189\ngo.etcd.io/etcd/server/v3/mvcc/backend.New\n\tgo.etcd.io/etcd/server/v3/mvcc/backend/backend.go:163\ngo.etcd.io/etcd/server/v3/etcdserver.newBackend\n\tgo.etcd.io/etcd/server/v3/etcdserver/backend.go:55\ngo.etcd.io/etcd/server/v3/etcdserver.openBackend.func1\n\tgo.etcd.io/etcd/server/v3/etcdserver/backend.go:76"}
panic: failed to open database
goroutine 146 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000ec840, {0xc0000a8300, 0x2, 0x2})
go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x49b
go.uber.org/zap.(*Logger).Panic(0xc0004cb3c8?, {0x10a47d1?, 0x18?}, {0xc0000a8300, 0x2, 0x2})
go.uber.org/zap@v1.17.0/logger.go:227 +0x59
go.etcd.io/etcd/server/v3/mvcc/backend.newBackend({{0xc0004cb3c8, 0x18}, 0x5f5e100, 0x2710, {0x10934d4, 0x7}, 0x233333333, 0xc0004c6fa0, 0x0, 0x0, ...})
go.etcd.io/etcd/server/v3/mvcc/backend/backend.go:189 +0x409
go.etcd.io/etcd/server/v3/mvcc/backend.New(...)
go.etcd.io/etcd/server/v3/mvcc/backend/backend.go:163
go.etcd.io/etcd/server/v3/etcdserver.newBackend({{0x7fff848cde7d, 0x17}, {0x0, 0x0}, {0x0, 0x0}, {0xc0004fdc20, 0x1, 0x1}, {0xc0004fde60, ...}, ...}, ...)
go.etcd.io/etcd/server/v3/etcdserver/backend.go:55 +0x399
go.etcd.io/etcd/server/v3/etcdserver.openBackend.func1()
go.etcd.io/etcd/server/v3/etcdserver/backend.go:76 +0x78
created by go.etcd.io/etcd/server/v3/etcdserver.openBackend
go.etcd.io/etcd/server/v3/etcdserver/backend.go:75 +0x18a

### Binary Version

```sh
"level":"panic","ts":"2023-09-25T08:07:08.960228Z","caller":"backend/backend.go:189","msg":"failed to open database","path":"/var/etcd/member/snap/db","error":"no locks available","stacktrace":"go.etcd.io/etcd/server/v3/mvcc/backend.newBackend\n\tgo.etcd.io/etcd/server/v3/mvcc/backend/backend.go:189\ngo.etcd.io/etcd/server/v3/mvcc/backend.New\n\tgo.etcd.io/etcd/server/v3/mvcc/backend/backend.go:163\ngo.etcd.io/etcd/server/v3/etcdserver.newBackend\n\tgo.etcd.io/etcd/server/v3/etcdserver/backend.go:55\ngo.etcd.io/etcd/server/v3/etcdserver.openBackend.func1\n\tgo.etcd.io/etcd/server/v3/etcdserver/backend.go:76"}
panic: failed to open database
goroutine 146 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000ec840, {0xc0000a8300, 0x2, 0x2})
go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x49b
go.uber.org/zap.(*Logger).Panic(0xc0004cb3c8?, {0x10a47d1?, 0x18?}, {0xc0000a8300, 0x2, 0x2})
go.uber.org/zap@v1.17.0/logger.go:227 +0x59
go.etcd.io/etcd/server/v3/mvcc/backend.newBackend({{0xc0004cb3c8, 0x18}, 0x5f5e100, 0x2710, {0x10934d4, 0x7}, 0x233333333, 0xc0004c6fa0, 0x0, 0x0, ...})
go.etcd.io/etcd/server/v3/mvcc/backend/backend.go:189 +0x409
go.etcd.io/etcd/server/v3/mvcc/backend.New(...)
go.etcd.io/etcd/server/v3/mvcc/backend/backend.go:163
go.etcd.io/etcd/server/v3/etcdserver.newBackend({{0x7fff848cde7d, 0x17}, {0x0, 0x0}, {0x0, 0x0}, {0xc0004fdc20, 0x1, 0x1}, {0xc0004fde60, ...}, ...}, ...)
go.etcd.io/etcd/server/v3/etcdserver/backend.go:55 +0x399
go.etcd.io/etcd/server/v3/etcdserver.openBackend.func1()
go.etcd.io/etcd/server/v3/etcdserver/backend.go:76 +0x78
created by go.etcd.io/etcd/server/v3/etcdserver.openBackend
go.etcd.io/etcd/server/v3/etcdserver/backend.go:75 +0x18a
```

### Operating System and Environment details

```sh
"level":"panic","ts":"2023-09-25T08:07:08.960228Z","caller":"backend/backend.go:189","msg":"failed to open database","path":"/var/etcd/member/snap/db","error":"no locks available","stacktrace":"go.etcd.io/etcd/server/v3/mvcc/backend.newBackend\n\tgo.etcd.io/etcd/server/v3/mvcc/backend/backend.go:189\ngo.etcd.io/etcd/server/v3/mvcc/backend.New\n\tgo.etcd.io/etcd/server/v3/mvcc/backend/backend.go:163\ngo.etcd.io/etcd/server/v3/etcdserver.newBackend\n\tgo.etcd.io/etcd/server/v3/etcdserver/backend.go:55\ngo.etcd.io/etcd/server/v3/etcdserver.openBackend.func1\n\tgo.etcd.io/etcd/server/v3/etcdserver/backend.go:76"}
panic: failed to open database
goroutine 146 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000ec840, {0xc0000a8300, 0x2, 0x2})
go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x49b
go.uber.org/zap.(*Logger).Panic(0xc0004cb3c8?, {0x10a47d1?, 0x18?}, {0xc0000a8300, 0x2, 0x2})
go.uber.org/zap@v1.17.0/logger.go:227 +0x59
go.etcd.io/etcd/server/v3/mvcc/backend.newBackend({{0xc0004cb3c8, 0x18}, 0x5f5e100, 0x2710, {0x10934d4, 0x7}, 0x233333333, 0xc0004c6fa0, 0x0, 0x0, ...})
go.etcd.io/etcd/server/v3/mvcc/backend/backend.go:189 +0x409
go.etcd.io/etcd/server/v3/mvcc/backend.New(...)
go.etcd.io/etcd/server/v3/mvcc/backend/backend.go:163
go.etcd.io/etcd/server/v3/etcdserver.newBackend({{0x7fff848cde7d, 0x17}, {0x0, 0x0}, {0x0, 0x0}, {0xc0004fdc20, 0x1, 0x1}, {0xc0004fde60, ...}, ...}, ...)
go.etcd.io/etcd/server/v3/etcdserver/backend.go:55 +0x399
go.etcd.io/etcd/server/v3/etcdserver.openBackend.func1()
go.etcd.io/etcd/server/v3/etcdserver/backend.go:76 +0x78
created by go.etcd.io/etcd/server/v3/etcdserver.openBackend
go.etcd.io/etcd/server/v3/etcdserver/backend.go:75 +0x18a
```

### Log Fragments

```sh
"level":"panic","ts":"2023-09-25T08:07:08.960228Z","caller":"backend/backend.go:189","msg":"failed to open database","path":"/var/etcd/member/snap/db","error":"no locks available","stacktrace":"go.etcd.io/etcd/server/v3/mvcc/backend.newBackend\n\tgo.etcd.io/etcd/server/v3/mvcc/backend/backend.go:189\ngo.etcd.io/etcd/server/v3/mvcc/backend.New\n\tgo.etcd.io/etcd/server/v3/mvcc/backend/backend.go:163\ngo.etcd.io/etcd/server/v3/etcdserver.newBackend\n\tgo.etcd.io/etcd/server/v3/etcdserver/backend.go:55\ngo.etcd.io/etcd/server/v3/etcdserver.openBackend.func1\n\tgo.etcd.io/etcd/server/v3/etcdserver/backend.go:76"}
panic: failed to open database
goroutine 146 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0000ec840, {0xc0000a8300, 0x2, 0x2})
go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x49b
go.uber.org/zap.(*Logger).Panic(0xc0004cb3c8?, {0x10a47d1?, 0x18?}, {0xc0000a8300, 0x2, 0x2})
go.uber.org/zap@v1.17.0/logger.go:227 +0x59
go.etcd.io/etcd/server/v3/mvcc/backend.newBackend({{0xc0004cb3c8, 0x18}, 0x5f5e100, 0x2710, {0x10934d4, 0x7}, 0x233333333, 0xc0004c6fa0, 0x0, 0x0, ...})
go.etcd.io/etcd/server/v3/mvcc/backend/backend.go:189 +0x409
go.etcd.io/etcd/server/v3/mvcc/backend.New(...)
go.etcd.io/etcd/server/v3/mvcc/backend/backend.go:163
go.etcd.io/etcd/server/v3/etcdserver.newBackend({{0x7fff848cde7d, 0x17}, {0x0, 0x0}, {0x0, 0x0}, {0xc0004fdc20, 0x1, 0x1}, {0xc0004fde60, ...}, ...}, ...)
go.etcd.io/etcd/server/v3/etcdserver/backend.go:55 +0x399
go.etcd.io/etcd/server/v3/etcdserver.openBackend.func1()
go.etcd.io/etcd/server/v3/etcdserver/backend.go:76 +0x78
created by go.etcd.io/etcd/server/v3/etcdserver.openBackend
go.etcd.io/etcd/server/v3/etcdserver/backend.go:75 +0x18a
```

**Comment by mattlord** [comment]
I'm going to close this as it is not a Vitess bug. This is a common/basic `etcd` issue — https://www.google.com/search?q=%22failed+to+open+database%22+%2Betcd — that is specific to your custom setup. This is also not the appropriate place to ask for general support/help. You should instead ask for help in the Vitess Slack: https://vitess.io/community/

Even then, you're the only one with the specific knowledge about how things are setup in your environment and with access to the system needed to debug it. That being said, there may be others that have similar setups and encountered the same issue who could help.

Some generic etcd notes  ...

etcd will create the datadir and its files if they do not exist and it has necessary permissions:
```
❯ etcd --name global --data-dir /tmp/pathnoexist --listen-client-urls http://localhost:16002 --advertise-client-urls http://localhost:16002 --initial-advertise-peer-urls http://localhost:16004 --listen-peer-urls http://localhost:16004 --initial-cluster global=http://localhost:16004
...

❯ ls -lR /tmp/pathnoexist
total 0
drwx------  4 matt  wheel  128 Oct 26 14:58 member

/tmp/pathnoexist/member:
total 0
drwx------  3 matt  wheel  96 Oct 26 14:58 snap
drwx------  3 matt  wheel  96 Oct 26 14:58 wal

/tmp/pathnoexist/member/snap:
total 192
-rw-------  1 matt  wheel  16891904 Oct 26 14:58 db

/tmp/pathnoexist/member/wal:
total 125000
-rw-------  1 matt  wheel  64000000 Oct 26 14:58 0000000000000000-0000000000000000.wal
```

If the directory doesn't exist and it cannot create it:
```
❯ etcd --name global --data-dir /pathnoexist --listen-client-urls http://localhost:16002 --advertise-client-urls http://localhost:16002 --initial-advertise-peer-
...
{"level":"fatal","ts":"2023-10-26T15:00:58.843867-0400","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"cannot access data directory: mkdir /pathnoexist: read-only file
```

You can play around with etcd directly in your environment. Note that the Vitess Operator uses an `etcdlockservice` CRD. You can get the logs for that service and its pods in your cluster to see what the lower level etcd issue is in your case.

For example, using the [operator examples](https://vitess.io/docs/18.0/get-started/operator/):
```
❯ kubectl get etcdlockservers
NAME                    AGE
example-etcd-faf13de3   47s

❯ kubectl describe etcdlockservers example-etcd-faf13de3 # to see the pods and PVC used

❯ kubectl logs example-etcd-faf13de3-1 | tail
{"level":"warn","ts":"2023-10-26T19:09:54.597946Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"8a3de6c453b6dbaa","rtt":"0s","error":"dial tcp: lookup example-etcd-faf13de3-2.example-etcd-faf13de3-peer on 10.96.0.10:53: no such host"}
{"level":"warn","ts":"2023-10-26T19:09:54.597971Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"8a3de6c453b6dbaa","rtt":"0s","error":"dial tcp: lookup example-etcd-faf13de3-2.example-etcd-faf13de3-peer on 10.96.0.10:53: no such host"}
{"level":"warn","ts":"2023-10-26T19:09:54.597973Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"9cd0550e45253e28","rtt":"0s","error":"dial tcp: lookup example-etcd-faf13de3-3.example-etcd-faf13de3-peer on 10.96.0.10:53: no such host"}
{"level":"warn","ts":"2023-10-26T19:09:54.599171Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"9cd0550e45253e28","rtt":"0s","error":"dial tcp: lookup example-etcd-faf13de3-3.example-etcd-faf13de3-peer on 10.96.0.10:53: no such host"}
{"level":"info","ts":"2023-10-26T19:09:54.60509Z","caller":"rafthttp/peer_status.go:53","msg":"peer became active","peer-id":"9cd0550e45253e28"}
{"level":"info","ts":"2023-10-26T19:09:54.605132Z","caller":"rafthttp/stream.go:412","msg":"established TCP streaming connection with remote peer","stream-reader-type":"stream MsgApp v2","local-member-id":"776a64628e1e9a42","remote-peer-id":"9cd0550e45253e28"}
{"level":"info","ts":"2023-10-26T19:09:54.605205Z","caller":"rafthttp/stream.go:412","msg":"established TCP streaming connection with remote peer","stream-reader-type":"stream Message","local-member-id":"776a64628e1e9a42","remote-peer-id":"9cd0550e45253e28"}
{"level":"info","ts":"2023-10-26T19:09:54.673462Z","caller":"etcdserver/server.go:2576","msg":"updating cluster version using v2 API","from":"3.0","to":"3.5"}
{"level":"info","ts":"2023-10-26T19:09:54.67432Z","caller":"membership/cluster.go:576","msg":"updated cluster version","cluster-id":"ffc80ca22604f156","local-member-id":"776a64628e1e9a42","from":"3.0","to":"3.5"}
{"level":"info","ts":"2023-10-26T19:09:54.674458Z","caller":"etcdserver/server.go:2595","msg":"cluster version is updated","cluster-version":"3.5"}
```

If this is not enough to allow you to find the problem then please ask in the Vitess Slack.
