### ISSUE TITLE
Bug Report: panic in vtctldclient PlannedReparentShard

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#14127]
### Overview of the Issue

```
vtctldclient --server localhost:15999 PlannedReparentShard workspaces/0
E0929 02:26:54.694464   83016 main.go:56] rpc error: code = Unknown desc = uncaught panic: runtime error: invalid memory address or nil pointer dereference
```

### Reproduction Steps

This panic happened when I tried to reparent to a shard that was shutdown

### Binary Version

```sh
vtctldclient version Version: 17.0.2 (Git revision  branch '') built on  by @ using go1.21.1 darwin/amd64

vtctld v15.0.2
```

### Operating System and Environment details

```sh
GKE v1.27
```

**Comment by wiebeytec** [comment]
This looks like the one I just had. For me, it was because the relevant tablet's MySQL wasn't running yet (which is the same as being shut down, I guess).

```
$ ./vtctldclient PlannedReparentShard --new-primary vic-eu-central-1-0000000501 unittest_sites/-80
E1215 15:21:05.248678  374160 main.go:56] rpc error: code = Unknown desc = uncaught panic: runtime error: invalid memory address or nil pointer dereference from: goroutine 26408 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
vitess.io/vitess/go/vt/vtctl/grpcvtctldserver.panicHandler(0xc0009c9950)
        vitess.io/vitess/go/vt/vtctl/grpcvtctldserver/server.go:117 +0x3d
panic({0x1d491a0?, 0x3e9e830?})
        runtime/panic.go:914 +0x21f
vitess.io/vitess/go/vt/vtctl/grpcvtctldserver.(*VtctldServer).PlannedReparentShard(0xc0009a8020, {0x2993060?, 0xc0010c41e0?}, 0xc000b00300)
        vitess.io/vitess/go/vt/vtctl/grpcvtctldserver/server.go:2744 +0x790
vitess.io/vitess/go/vt/proto/vtctlservice._Vtctld_PlannedReparentShard_Handler({0x2081d60?, 0xc0009a8020}, {0x2993060, 0xc0010c41e0}, 0xc0006289a0, 0x0)
        vitess.io/vitess/go/vt/proto/vtctlservice/vtctlservice_grpc.pb.go:3318 +0x16c
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00071c1e0, {0x299ef20, 0xc000fcc9c0}, 0xc00107c000, 0xc000996120, 0x3ed88e0, 0x0)
        google.golang.org/grpc@v1.55.0-dev/server.go:1345 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc00071c1e0, {0x299ef20, 0xc000fcc9c0}, 0xc00107c000, 0x0)
        google.golang.org/grpc@v1.55.0-dev/server.go:1722 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.55.0-dev/server.go:966 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 26394
        google.golang.org/grpc@v1.55.0-dev/server.go:964 +0x246
```

```
./vtctldclient --version
vtctldclient version Version: 18.0.0 (Git revision 9a6f5262f7707ff80ce85c111d2ff686d85d29cc branch 'HEAD') built on Mon Nov  6 12:16:43 UTC 2023 by runner@fv-az422-64 using go1.21.3 linux/amd64
```
