### ISSUE TITLE
Flaky TestMtlsAuthUnauthorizedFails

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/vitess#14811]
### Overview of the Issue

```
I1218 13:22:51.278055   47497 tracker.go:165] Starting schema tracking
I1218 13:22:51.278087   47497 grpc_server.go:286] Listening for gRPC calls on port 24845
I1218 13:22:51.278163   47497 unix_socket.go:37] Not listening on socket file
F1218 13:22:51.278212   47497 run.go:50] listen tcp :24844: bind: address already in use
panic: test timed out after 10m0s
running tests:
	TestMtlsAuthUnauthorizedFails (8m56s)

goroutine 1504 [running]:
testing.(*M).startAlarm.func1()
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/testing/testing.go:2241 +0x219
created by time.goFunc
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 8 minutes]:
testing.(*T).Run(0xc000503ba0, {0x202accc, 0x1d}, 0x2310338)
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/testing/testing.go:1630 +0x82e
testing.runTests.func1(0x0?)
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/testing/testing.go:2036 +0x8e
testing.tRunner(0xc000503ba0, 0xc000167b48)
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/testing/testing.go:1576 +0x217
testing.runTests(0xc000742000?, {0x36db480, 0x7, 0x7}, {0x1c?, 0x4accd9?, 0x3730cc0?})
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/testing/testing.go:2034 +0x87d
testing.(*M).Run(0xc000742000)
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/testing/testing.go:1906 +0xb45
main.main()
	_testmain.go:59 +0x2ea

goroutine 19 [select, 2 minutes]:
github.com/golang/glog.(*fileSink).flushDaemon(0x3730bd8)
	/home/ubuntu/go/pkg/mod/github.com/golang/glog@v1.1.2/glog_file.go:351 +0x170
created by github.com/golang/glog.init.1
	/home/ubuntu/go/pkg/mod/github.com/golang/glog@v1.1.2/glog_file.go:166 +0x23d

goroutine 31 [syscall, 10 minutes]:
os/signal.signal_recv()
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/os/signal/signal.go:151 +0x51

goroutine 32 [chan receive, 10 minutes]:
vitess.io/vitess/go/vt/dbconfigs.init.0.func1()
	/opt/actions-runner/_work/vitess-private/vitess-private/go/vt/dbconfigs/credentials.go:90 +0x45
created by vitess.io/vitess/go/vt/dbconfigs.init.0
	/opt/actions-runner/_work/vitess-private/vitess-private/go/vt/dbconfigs/credentials.go:89 +0x257

goroutine 1415 [chan receive, 8 minutes]:
vitess.io/vitess/go/vt/vttest.(*VtProcess).WaitTerminate(0xc00083cfa0)
	/opt/actions-runner/_work/vitess-private/vitess-private/go/vt/vttest/vtprocess.go:115 +0x2e5
vitess.io/vitess/go/vt/vttest.(*LocalCluster).TearDown(0xc000753bb8)
	/opt/actions-runner/_work/vitess-private/vitess-private/go/vt/vttest/local_cluster.go:395 +0x9a
vitess.io/vitess/go/cmd/vttestserver.TestMtlsAuthUnauthorizedFails(0xc000238820)
	/opt/actions-runner/_work/vitess-private/vitess-private/go/cmd/vttestserver/vttestserver_test.go:298 +0x9aa
testing.tRunner(0xc000238820, 0x2310338)
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/testing/testing.go:1576 +0x217
created by testing.(*T).Run
	/opt/actions-runner/_work/_tool/go/1.20.12/x64/src/testing/testing.go:1629 +0x806
FAIL	vitess.io/vitess/go/cmd/vttestserver	600.110s



E1218 13:52:47.185626   51965 throttler.go:915] refreshMySQLInventory: context canceled
E1218 13:52:47.185717   51965 throttler.go:915] refreshMySQLInventory: context canceled
==================
WARNING: DATA RACE
Write at 0x0000031cdef0 by goroutine 5711:
  vitess.io/vitess/go/vt/vttablet/tabletserver/throttle.newTestThrottler()
      /home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/throttle/throttler_test.go:103 +0x21c
  vitess.io/vitess/go/vt/vttablet/tabletserver/throttle.TestProbesWhileOperating()
      /home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/throttle/throttler_test.go:356 +0x29
  testing.tRunner()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x261
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x44

Previous read at 0x0000031cdef0 by goroutine 83:
  vitess.io/vitess/go/vt/vttablet/tabletserver/throttle.(*Throttler).refreshMySQLInventory()
      /home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/throttle/throttler.go:862 +0x18f
  vitess.io/vitess/go/vt/vttablet/tabletserver/throttle.(*Throttler).Operate.func2()
      /home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/throttle/throttler.go:727 +0xa47

Goroutine 5711 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x845
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:2054 +0x84
  testing.tRunner()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x261
  testing.runTests()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:2052 +0x8ad
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1925 +0xcd7
  main.main()
      _testmain.go:61 +0x2bd

```

### Binary Version

```sh
This was in `latest-16.0`
```

**Comment by rohit-nayak-ps** [comment]
We are not seeing this now
