### ISSUE TITLE
flaky test "vtgatev2_l2vtgate": ExecuteFetch(START SLAVE) failed: Slave failed to initialize relay log info structure from the repository (errno 1872) (sqlstate HY000) during query: START SLAVE

### ISSUE THREAD

**Issue by michael-berlin** [vitessio/vitess#3237]
The test just failed on me three times in a row.

Here's a re-run of the Travis build where it only failed once: https://travis-ci.org/youtube/vitess/jobs/278857824

I haven't looked further into the cause yet or how to fix it.

I'm just filing this bug to raise awareness.

Stacktrace:

```
-- 2017-09-23 05:09:57,609 utils:79 INFO ===== test_kill_mysql_tablet_queries_multi_tablets (vtgatev2_test.TestFailures) ... 
-- 2017-09-23 05:09:57,609 vtgatev2_test:341 INFO Start: TestFailures.test_kill_mysql_tablet_queries_multi_tablets.
-- 2017-09-23 05:09:57,610 utils:306 DEBUG run: ['/vt/bin/mysqlctl', '-log_dir', '/vt/vtdataroot/tmp', '-tablet_uid', '62348', '-port', '15012', '-mysql_port', '15013', '-db-config-dba-uname', 'vt_dba', '-db-config-dba-charset', 'utf8', 'shutdown'] extra_env={'EXTRA_MY_CNF': '/vt/src/github.com/youtube/vitess/config/mycnf/default-fast.cnf:/vt/src/github.com/youtube/vitess/config/mycnf/master_mysql56.cnf'}
I0923 05:10:00.025642    9921 throttled.go:77] ExecuteKeyRanges: skipped 43 log messages
-- 2017-09-23 05:10:09,651 utils:306 DEBUG run: ['/vt/bin/mysqlctl', '-log_dir', '/vt/vtdataroot/tmp', '-tablet_uid', '62348', '-port', '15012', '-mysql_port', '15013', '-db-config-dba-uname', 'vt_dba', '-db-config-dba-charset', 'utf8', 'start'] extra_env={'EXTRA_MY_CNF': '/vt/src/github.com/youtube/vitess/config/mycnf/default-fast.cnf:/vt/src/github.com/youtube/vitess/config/mycnf/master_mysql56.cnf'}
-- 2017-09-23 05:10:10,792 utils:267 DEBUG run: ['/vt/bin/vtctl', '-log_dir', '/vt/vtdataroot/tmp', '-enable_queries', '-topo_implementation', 'zk2', '-topo_global_server_address', 'localhost:15020', '-topo_global_root', '/global', '-tablet_manager_protocol', 'grpc', '-tablet_protocol', 'grpc', '-throttler_client_protocol', 'grpc', '-vtgate_protocol', 'grpc', '--wait_for_drain_sleep_rdonly', '0s', '--wait_for_drain_sleep_replica', '0s', 'StartSlave', 'test_nj-0000062348'] 
E0923 05:10:10.822724   14928 vtctl.go:112] action failed: StartSlave rpc error: code = Unknown desc = TabletManager.StartSlave on test_nj-0000062348 error: ExecuteFetch(START SLAVE) failed: Slave failed to initialize relay log info structure from the repository (errno 1872) (sqlstate HY000) during query: START SLAVE
-- 2017-09-23 05:10:10,840 utils:79 INFO ===== test_kill_mysql_tablet_queries_multi_tablets (vtgatev2_test.TestFailures) ... ERROR
-- 2017-09-23 05:10:10,841 vtgatev2_test:150 DEBUG in tearDownModule
-- 2017-09-23 05:10:10,841 utils:79 INFO ===== ======================================================================
-- 2017-09-23 05:10:10,841 utils:79 INFO ===== ERROR: test_kill_mysql_tablet_queries_multi_tablets (vtgatev2_test.TestFailures)
-- 2017-09-23 05:10:10,841 utils:79 INFO ===== ----------------------------------------------------------------------
-- 2017-09-23 05:10:10,841 utils:79 INFO ===== Traceback (most recent call last):
  File "/vt/src/github.com/youtube/vitess/test/vtgatev2_test.py", line 1412, in test_kill_mysql_tablet_queries_multi_tablets
    utils.run_vtctl(['StartSlave', t.tablet_alias])
  File "/vt/src/github.com/youtube/vitess/test/utils.py", line 912, in run_vtctl
    expect_fail=expect_fail, **kwargs)
  File "/vt/src/github.com/youtube/vitess/test/utils.py", line 955, in run_vtctl_vtctl
    return run(cmd, **kwargs)
  File "/vt/src/github.com/youtube/vitess/test/utils.py", line 274, in run
    raise TestError('cmd fail:', args, proc.returncode, stdout, stderr)
TestError: ('cmd fail:', ['/vt/bin/vtctl', '-log_dir', '/vt/vtdataroot/tmp', '-enable_queries', '-topo_implementation', 'zk2', '-topo_global_server_address', 'localhost:15020', '-topo_global_root', '/global', '-tablet_manager_protocol', 'grpc', '-tablet_protocol', 'grpc', '-throttler_client_protocol', 'grpc', '-vtgate_protocol', 'grpc', '--wait_for_drain_sleep_rdonly', '0s', '--wait_for_drain_sleep_replica', '0s', 'StartSlave', 'test_nj-0000062348'], 255, None, None)
```

**Comment by sougou** [comment]
The test is now obsolete and deleted.
