### ISSUE TITLE
flaky test: TestParallelRunnerApprovalFirstRunningSecondRunning

### ISSUE THREAD

**Issue by demmer** [vitessio/vitess#4324]
I got the following error in Travis which passed after re-running the job:

```
--- FAIL: TestParallelRunnerApprovalFirstRunningSecondRunning (0.01s)
panic: close of closed channel [recovered]
	panic: close of closed channel
goroutine 87 [running]:
testing.tRunner.func1(0xc420206870)
	/usr/local/go/src/testing/testing.go:742 +0x567
panic(0xb47a00, 0xc7b040)
	/usr/local/go/src/runtime/panic.go:502 +0x24a
vitess.io/vitess/go/vt/workflow.TestParallelRunnerApprovalFirstRunningSecondRunning(0xc420206870)
	/vt/src/vitess.io/vitess/go/vt/workflow/parallel_runner_test.go:363 +0xa4d
testing.tRunner(0xc420206870, 0xc16698)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565
```

**Comment by deepthi** [comment]
@rohit-nayak-ps can this be closed?

**Comment by rohit-nayak-ps** [comment]
I haven't worked on this one. This has never occurred for me though.

**Comment by rohit-nayak-ps** [comment]
We are not seeing this anymore
