### ISSUE TITLE
Message Manager Panic

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4436]
This isn't urgent, but I wanted to record it while I had a stacktrace. I made a change to the underlying messages table and added a field, which eventually caused a panic downstream.

```
 panic: runtime error: index out of range

 goroutine 211 [running]:
 /vendor/vitess.io/vitess/go/sqltypes.MakeRowTrusted(0xc0007dc5c0, 0x5, 0x8, 0xc000732ae0, 0x1, 0x1, 0x0)
 	/vendor/vitess.io/vitess/go/sqltypes/result.go:194 +0x171
 /vendor/vitess.io/vitess/go/sqltypes.proto3ToRows(0xc0007dc5c0, 0x5, 0x8, 0xc0002f2048, 0x1, 0x1, 0xc000769dd8, 0xd32dff, 0xc000265240)
 	/vendor/vitess.io/vitess/go/sqltypes/proto3.go:79 +0xc5
 /vendor/vitess.io/vitess/go/sqltypes.CustomProto3ToResult(0xc0007dc5c0, 0x5, 0x8, 0xc0006743c0, 0x0)
 	/vendor/vitess.io/vitess/go/sqltypes/proto3.go:124 +0x72
 /vendor/vitess.io/vitess/go/vt/vtgate/grpcvtgateconn.(*streamExecuteAdapter).Recv(0xc0001e83e0, 0x0, 0x0, 0x0)
 	/vendor/vitess.io/vitess/go/vt/vtgate/grpcvtgateconn/conn.go:286 +0x75
 /vendor/vitess.io/vitess/go/vt/vitessdriver.(*streamingRows).Next(0xc0002e6910, 0xc00051c640, 0x5, 0x5, 0x5, 0x5)
 	/vendor/vitess.io/vitess/go/vt/vitessdriver/streaming_rows.go:76 +0xd0
 database/sql.(*Rows).nextLocked(0xc000738600, 0xc0002d0000)
 	/usr/local/Cellar/go/1.11.2/libexec/src/database/sql/sql.go:2665 +0xc1
 database/sql.(*Rows).Next.func1()
 	/usr/local/Cellar/go/1.11.2/libexec/src/database/sql/sql.go:2643 +0x3c
 database/sql.withLock(0x11e53a0, 0xc000738630, 0xc00077ff38)
 	/usr/local/Cellar/go/1.11.2/libexec/src/database/sql/sql.go:3076 +0x63
 database/sql.(*Rows).Next(0xc000738600, 0x10b24e8)
 	/usr/local/Cellar/go/1.11.2/libexec/src/database/sql/sql.go:2642 +0x87
 /vendor/vitess.io/messages.(*Queue).Open.func1(0xc000738600, 0xc000164a50)
 	/vendor/vitess.io/messages/subscription.go:64 +0xef
 created by /vendor/vitess.io/messages.(*Queue).Open
 	/vendor/vitess.io/messages/subscription.go:59 +0x19e
```

**Comment by derekperkins** [comment]
Yeah, I knew that live changes weren't supported. At some point, I plan to go in and add support for live changes to schemas and the messages meta fields.
