### ISSUE TITLE
panic in vtctld startup

### ISSUE THREAD

**Issue by slanning** [vitessio/vitess#4518]
When starting vtctld, it outputs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb25f36]

goroutine 76 [running]:
vitess.io/vitess/go/vt/workflow.(*Manager).Run(0xc0003c8180, 0x11f3f20, 0xc0003c82c0)
       vitess.io/vitess/go/vt/workflow/manager.go:187 +0x1e6
vitess.io/vitess/go/vt/vtctld.runWorkflowManagerElection.func1.2(0xc0003f8310)
        vitess.io/vitess/go/vt/vtctld/workflow.go:127 +0x140
created by vitess.io/vitess/go/vt/vtctld.runWorkflowManagerElection.func1
        vitess.io/vitess/go/vt/vtctld/workflow.go:122 +0x2a0
```
The vtctld continues running, somehow, and seems otherwise normal; though, when killing (TERM) the process it doesn't remove the pid_file.

**Comment by slanning** [comment]
This is with etcd

**Comment by slanning** [comment]
I think I mis-read the log output before... The vtctld seems to be running, then when it's shut down the panic occurs.

**Comment by ejortegau** [comment]
Seeing something similar in 12.0.5:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1927957]
goroutine 89 [running]:
vitess.io/vitess/go/vt/workflow.(*Manager).Run(0xc0004ff040, {0x2bacfe8, 0xc050fcbec0})
\tvitess.io/vitess/go/vt/workflow/manager.go:186 +0x237
vitess.io/vitess/go/vt/vtctld.runWorkflowManagerElection.func1.2()
\tvitess.io/vitess/go/vt/vtctld/workflow.go:127 +0x4f
created by vitess.io/vitess/go/vt/vtctld.runWorkflowManagerElection.func1
\tvitess.io/vitess/go/vt/vtctld/workflow.go:122 +0x2c7
```
though this is happening when no terminations or restarts of the vtctld process seem to be happening
