### ISSUE TITLE
vtgate query planner panic for count of (join + order by)

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#4851]
Failing test case for go/vt/vtgate/planbuilder/testdata/aggr_cases.txt:

`"select count(*) from (select col, user_extra.extra from user join user_extra on user.id = user_extra.user_id order by user_extra.extra) a"`

Output:

```
$  go test vitess.io/vitess/go/vt/vtgate/planbuilder -run "^(TestPlan)$"
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 59 [running]:
testing.tRunner.func1(0xc00031f000)
	/home/dweitzman/bin/go1.11/src/testing/testing.go:792 +0x387
panic(0x934900, 0xfa5260)
	/home/dweitzman/bin/go1.11/src/runtime/panic.go:513 +0x1b9
vitess.io/vitess/go/vt/vtgate/planbuilder.(*route).Wireup(0xc000338480, 0xa77160, 0xc00033ca20, 0xc00032dea0, 0x0, 0x0)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/route.go:377 +0xcd3
vitess.io/vitess/go/vt/vtgate/planbuilder.(*orderedAggregate).Wireup(0xc00033ca20, 0xa77160, 0xc00033ca20, 0xc00032dea0, 0x0, 0x40e148)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/ordered_aggregate.go:469 +0xfc
vitess.io/vitess/go/vt/vtgate/planbuilder.buildSelectPlan(0xc000329520, 0xa73b60, 0xc000126640, 0xe0829d, 0x31, 0x8, 0x8)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/select.go:33 +0x128
vitess.io/vitess/go/vt/vtgate/planbuilder.BuildFromStmt(0xc0001fa480, 0x89, 0xa72420, 0xc000329520, 0xa73b60, 0xc000126640, 0x94d2e0, 0x1, 0xc000126640)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/builder.go:138 +0x425
vitess.io/vitess/go/vt/vtgate/planbuilder.Build(0xc0001fa480, 0x89, 0xa73b60, 0xc000126640, 0xe0829d, 0x31, 0x2f7)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/builder.go:124 +0x97
vitess.io/vitess/go/vt/vtgate/planbuilder.testFile.func1(0xc00031f000)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/plan_test.go:225 +0xb5
testing.tRunner(0xc00031f000, 0xc00033c4b0)
	/home/dweitzman/bin/go1.11/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/home/dweitzman/bin/go1.11/src/testing/testing.go:878 +0x353
FAIL	vitess.io/vitess/go/vt/vtgate/planbuilder	0.013s
```

**Comment by sougou** [comment]
There is an underlying bug in the older code that this panic is exposing: the inner query is a merge-sort of a scatter query, which is technically not a route.

The older code would push down constructs that are valid to be pushed for a scatter query. But that would be incorrect in some cases if there's a merge-sort in between.

To solve this, I'm thinking of creating a new primitive called `MergeSort`, which will take a `Route` as input. This will automatically cause some queries that previously worked to fail. I believe it's the right thing because those failures would have otherwise returned incorrect results.
