### ISSUE TITLE
vcopier unit test failing in percona 5.6

### ISSUE THREAD

**Issue by dweitzman** [vitessio/vitess#4852]
Works in 5.7:

```
$ docker run -it vitess/base:percona57 bash -c 'go test -timeout 30s vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication -run "^(TestPlayerCopyTableContinuation)$"'
ok  	vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication	9.170s
```

Fails in 5.6:

```
$ docker run -it vitess/base:percona bash -c 'go test -timeout 30s vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication -run "^(TestPlayerCopyTableContinuation)$"'
ERROR: logging before flag.Parse: E0501 20:17:23.702005    1144 syslogger.go:122] can't connect to syslog
E0501 20:17:23.712169    1144 syslogger.go:84] no connection, dropping syslog event: &events.KeyspaceChange{KeyspaceName:"vttest", Keyspace:(*topodata.Keyspace)(0xc0000ad950), Status:"created"}
E0501 20:17:23.713566    1144 syslogger.go:84] no connection, dropping syslog event: &events.ShardChange{KeyspaceName:"vttest", ShardName:"0", Shard:(*topodata.Shard)(0xc0001ba480), Status:"created"}
E0501 20:17:33.658970    1144 syslogger.go:84] no connection, dropping syslog event: &events.TabletChange{Tablet:topodata.Tablet{Alias:(*topodata.TabletAlias)(0xc0001d0c40), Hostname:"", PortMap:map[string]int32{"test":100}, Keyspace:"vttest", Shard:"0", KeyRange:(*topodata.KeyRange)(nil), Type:2, DbNameOverride:"", Tags:map[string]string{"serving":"serving", "healthy":"healthy"}, MysqlHostname:"", MysqlPort:0, XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:74}, Status:"created"}
E0501 20:17:33.785504    1144 controller.go:134] stream 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where (1,1) <= (6,6)' at line 1 (errno 1064) (sqlstate 42000) during query: insert into dst1(id,val) select 1, 'insert in' where (1,1) <= (6,6), retrying after 5s
panic: test timed out after 30s

goroutine 8144 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1296 +0xfd
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00013b200, 0xcc2230, 0x1f, 0xcf1d60, 0x48e601)
	/usr/local/go/src/testing/testing.go:879 +0x383
testing.runTests.func1(0xc00013b100)
	/usr/local/go/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc00013b100, 0xc0001cfca0)
	/usr/local/go/src/testing/testing.go:827 +0xbf
testing.runTests(0xc0002d2520, 0x14cdb20, 0x29, 0x29, 0xc0002ca750)
	/usr/local/go/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc0001ba300, 0x0)
	/usr/local/go/src/testing/testing.go:1034 +0x165
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.TestMain.func1(0xc0001ba300, 0x0)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/framework_test.go:116 +0x887
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.TestMain(0xc0001ba300)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/framework_test.go:117 +0x30
main.main()
	_testmain.go:120 +0x13d

goroutine 5 [chan receive]:
vitess.io/vitess/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x14dba20)
	/vt/src/vitess.io/vitess/vendor/github.com/golang/glog/glog.go:882 +0x8b
created by vitess.io/vitess/vendor/github.com/golang/glog.init.0
	/vt/src/vitess.io/vitess/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 80 [chan send]:
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*realDBClient).ExecuteFetch(0xc000381250, 0xcad622, 0x8, 0x2710, 0x42d541, 0xcf1c10, 0xc0003b9a00)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/framework_test.go:358 +0x10e
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*realDBClient).Rollback(0xc000381250, 0xc0003552c0, 0xc0003b9a00)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/framework_test.go:343 +0x49
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*vdbClient).Rollback(0xc0003bc640, 0xa, 0xc0000bf540)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vdbclient.go:67 +0x33
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*vcopier).copyTable(0xc0000bca50, 0xd9f2e0, 0xc0003c5200, 0xc0000738f1, 0x4, 0xc00045c1b0, 0x0, 0x0)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vcopier.go:274 +0x8ef
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*vcopier).copyNext(0xc0000bca50, 0xd9f260, 0xc0001d12c0, 0xda2d60, 0xc00045c150, 0x0, 0x0, 0x7fffffffffffffff, 0x7fffffffffffffff, 0xc0000738dc, ...)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vcopier.go:114 +0x329
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*vreplicator).Replicate(0xc0003a07c0, 0xd9f260, 0xc0001d12c0, 0x2710, 0xc0003bc5f0)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go:98 +0x39b
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*controller).runBlp(0xc0001dd5e0, 0xd9f260, 0xc0001d12c0, 0x0, 0x0)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/controller.go:198 +0x355
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*controller).run(0xc0001dd5e0, 0xd9f260, 0xc0001d12c0)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/controller.go:124 +0x87
created by vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.newController
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/controller.go:111 +0x43a

goroutine 79 [select]:
vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).watch(0xc0002ec580)
	/vt/src/vitess.io/vitess/go/vt/discovery/topology_watcher.go:165 +0x13f
created by vitess.io/vitess/go/vt/discovery.NewTopologyWatcher
	/vt/src/vitess.io/vitess/go/vt/discovery/topology_watcher.go:154 +0x1b6

goroutine 26 [chan receive]:
vitess.io/vitess/go/vt/dbconfigs.init.0.func1(0xc00017a8a0)
	/vt/src/vitess.io/vitess/go/vt/dbconfigs/credentials.go:136 +0x41
created by vitess.io/vitess/go/vt/dbconfigs.init.0
	/vt/src/vitess.io/vitess/go/vt/dbconfigs/credentials.go:135 +0x11b

goroutine 74 [chan receive]:
vitess.io/vitess/go/stats.(*Rates).track(0xc000300180)
	/vt/src/vitess.io/vitess/go/stats/rates.go:99 +0x54
created by vitess.io/vitess/go/stats.NewRates
	/vt/src/vitess.io/vitess/go/stats/rates.go:91 +0x1f2

goroutine 29 [chan receive]:
vitess.io/vitess/go/stats.(*Rates).track(0xc00017b5c0)
	/vt/src/vitess.io/vitess/go/stats/rates.go:99 +0x54
created by vitess.io/vitess/go/stats.NewRates
	/vt/src/vitess.io/vitess/go/stats/rates.go:91 +0x1f2

goroutine 35 [select]:
vitess.io/vitess/go/timer.(*Timer).run(0xc00016ba60, 0xc000171fb0)
	/vt/src/vitess.io/vitess/go/timer/timer.go:98 +0xc3
created by vitess.io/vitess/go/timer.(*Timer).Start
	/vt/src/vitess.io/vitess/go/timer/timer.go:86 +0xa9

goroutine 50 [chan receive]:
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*controller).Stop(0xc0001dd5e0)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/controller.go:205 +0x4c
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*Engine).Exec(0xc0001bae00, 0xc0003ba420, 0x29, 0x0, 0x0, 0x0)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/engine.go:286 +0x8f4
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.TestPlayerCopyTableContinuation.func3(0x1, 0xc00013b200)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go:219 +0xb3
runtime.Goexit()
	/usr/local/go/src/runtime/panic.go:397 +0xef
testing.(*common).FailNow(0xc00013b200)
	/usr/local/go/src/testing/testing.go:590 +0x39
testing.(*common).Fatalf(0xc00013b200, 0xcc75ff, 0x23, 0xc0001cb988, 0x2, 0x2)
	/usr/local/go/src/testing/testing.go:634 +0x83
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.expectData(0xc00013b200, 0xca8ce5, 0x4, 0xc00035eb60, 0x9, 0x9)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/framework_test.go:465 +0x74f
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.TestPlayerCopyTableContinuation(0xc00013b200)
	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vcopier_test.go:263 +0x12a4
testing.tRunner(0xc00013b200, 0xcf1d60)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x35c

goroutine 36 [select]:
vitess.io/vitess/go/timer.(*Timer).run(0xc00016bcc0, 0xc0002ca180)
	/vt/src/vitess.io/vitess/go/timer/timer.go:98 +0xc3
created by vitess.io/vitess/go/timer.(*Timer).Start
	/vt/src/vitess.io/vitess/go/timer/timer.go:86 +0xa9

goroutine 83 [select]:
vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).checkConn(0xc000300660, 0xc0001595e0, 0xc0002c7f60, 0x10)
	/vt/src/vitess.io/vitess/go/vt/discovery/healthcheck.go:571 +0x380
created by vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).AddTablet
	/vt/src/vitess.io/vitess/go/vt/discovery/healthcheck.go:749 +0x44c

goroutine 108 [chan receive]:
vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema.func1(0xc0000adb80, 0xd9f2a0, 0xc000038078, 0xca9870, 0x5, 0xc000380330, 0xc000325950)
	/vt/src/vitess.io/vitess/go/vt/srvtopo/resilient_server.go:536 +0x260
created by vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema
	/vt/src/vitess.io/vitess/go/vt/srvtopo/resilient_server.go:520 +0xb1

goroutine 109 [chan receive]:
vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema.func1(0xc000384540, 0xc000384420, 0xc00036e840)
	/vt/src/vitess.io/vitess/go/vt/topo/srv_vschema.go:68 +0xae
created by vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema
	/vt/src/vitess.io/vitess/go/vt/topo/srv_vschema.go:65 +0x359

goroutine 110 [select]:
vitess.io/vitess/go/timer.(*Timer).run(0xc000365080, 0xc000380850)
	/vt/src/vitess.io/vitess/go/timer/timer.go:98 +0xc3
created by vitess.io/vitess/go/timer.(*Timer).Start
	/vt/src/vitess.io/vitess/go/timer/timer.go:86 +0xa9

goroutine 111 [select]:
vitess.io/vitess/go/timer.(*Timer).run(0xc0003650a0, 0xc000380870)
	/vt/src/vitess.io/vitess/go/timer/timer.go:98 +0xc3
created by vitess.io/vitess/go/timer.(*Timer).Start
	/vt/src/vitess.io/vitess/go/timer/timer.go:86 +0xa9

goroutine 118 [select]:
vitess.io/vitess/go/timer.(*Timer).run(0xc00016bce0, 0xc000365420)
	/vt/src/vitess.io/vitess/go/timer/timer.go:98 +0xc3
created by vitess.io/vitess/go/timer.(*Timer).Start
	/vt/src/vitess.io/vitess/go/timer/timer.go:86 +0xa9
FAIL	vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication	39.977s
```

**Comment by dweitzman** [comment]
I _think_ `insert into dst1(id,val) select 1, 'insert in' where (1,1) <= (6,6)` might need to be changed to `insert into dst1(id,val) select 1, 'insert in' from dual where (1,1) <= (6,6)` for mysql 5.6

The first one doesn't parse and the second one does parse, at least.
