### ISSUE TITLE
Vitess client is not able to identify correct datatype of "Date type" in Mysql when Hibernate is used as ORM

### ISSUE THREAD

**Issue by dhruv-bansal** [vitessio/vitess#5128]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue
I am using hibernate as ORM. I have an entity (in java) which defines variable with datatype Local date

```
@Column(name = "VALID_DATE_FROM", nullable = false)
    @JsonDeserialize(using = LocalDateDeserializer.class)
    @JsonSerialize(using = LocalDateSerializer.class)
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate validDateFrom;
```

Now using this java application, with vitess client (3.0.0) now I am trying to get the records from the Table which defines the column (corresponding to above-mentioned property in Entity) 
 `valid_DATE_FROM date NOT NULL,`

Now while fetching the data from java application I am getting the following error.

C

> aused by: org.hibernate.exception.DataException: could not execute query
> 	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:52)
> 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
> 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
> 	at org.hibernate.loader.Loader.doList(Loader.java:2695)
> 	at org.hibernate.loader.Loader.doList(Loader.java:2675)
> 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2507)
> 	at org.hibernate.loader.Loader.list(Loader.java:2502)
> 	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:502)
> 	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:392)
> 	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
> 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1490)
> 	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1445)
> 	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1414)
> 	... 267 common frames omitted
> Caused by: java.sql.SQLDataException: type mismatch, expected: TIMESTAMP or DATETIME, actual: DATE
> 	at io.vitess.client.cursor.Row.getTimestamp(Row.java:486)
> 	at io.vitess.client.cursor.Row.getTimestamp(Row.java:470)
> 	at io.vitess.jdbc.VitessResultSet.getNullableDateTime(VitessResultSet.java:859)
> 	at io.vitess.jdbc.VitessResultSet.getTimestamp(VitessResultSet.java:499)
> 	at io.vitess.jdbc.VitessResultSet.getTimestamp(VitessResultSet.java:569)
> 	at com.zaxxer.hikari.pool.HikariProxyResultSet.getTimestamp(HikariProxyResultSet.java)

**Comment by ljluestc** [comment]
```

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateSerializer;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import java.time.LocalDate;

@Entity
@Table(name = "my_alarms_timeline")
public class MyAlarm {

    @Id
    private Long id; // Assuming an ID field exists

    @Column(name = "VALID_DATE_FROM", nullable = false)
    @JsonDeserialize(using = LocalDateDeserializer.class)
    @JsonSerialize(using = LocalDateSerializer.class)
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate validDateFrom;

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDate getValidDateFrom() {
        return validDateFrom;
    }

    public void setValidDateFrom(LocalDate validDateFrom) {
        this.validDateFrom = validDateFrom;
    }
}
```
