### ISSUE TITLE
resharding_bytes test is flaky

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#5357]
This test fails intermittently on travis CI.
```
INFO:root:===== ----------------------------------------------------------------------
INFO:root:===== Traceback (most recent call last):
  File "/vt/src/vitess.io/vitess/test/resharding.py", line 1229, in test_resharding
    0x9000000000000000)
  File "/vt/src/vitess.io/vitess/test/base_sharding.py", line 139, in _check_value
    keyspace_id, str(result)))
AssertionError: Bad row in tablet test_nj-0000062347 for id=2, custom_ksid_col=�, row=()
INFO:root:===== ----------------------------------------------------------------------
INFO:root:===== Ran 1 test in 190.523s
INFO:root:===== FAILED
INFO:root:===== FAILED (failures=1)
WARNING:root:Leaving temporary files behind (--keep-logs), please clean up before next run: /vt/vtdataroot
2019/10/25 15:42:01 mysql57.resharding_bytes: saving test output to _test/20191025-152130.3920/mysql57.resharding_bytes-1.1.log
2019/10/25 15:42:01 mysql57.resharding_bytes: FAILED (try 1/3) in 3m15s: exit status 255
```

**Comment by deepthi** [comment]
@sougou can you evaluate whether this should be disabled until it is rewritten to use v3 resharding?

**Comment by sougou** [comment]
This now obsolete :)
