### ISSUE TITLE
MySQL Workbench: Support fully qualified object names (schema.table etc)

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5393]
#### Feature Description

MySQL workbench requires Vitess to support the command `SHOW FULL COLUMNS FROM database.table`. Vitess only supports this command without the database name, resulting in an error:
```
"Unknown database 'commerce' (errno 1049) (sqlstate 42000) (CallerID: userData1): Sql: \"SHOW FULL COLUMNS FROM `commerce`.`cache_bootstrap`\", BindVars:
```

**Comment by morgo** [comment]
Sorry, I misunderstood the cause. The issue is that while this command can be routed directly to MySQL it uses the keyspace name of `commerce`, which MySQL does not have (it has `vt_commerce`).

So there needs to be a rewrite to send to MySQL as `vt_commerce` (the schema name used on the tablet).

**Comment by morgo** [comment]
This also exists when trying a fully qualified name for a table:
```
mysql> show create table product;
+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                                                                                                                         |
+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| product | CREATE TABLE `product` (
  `sku` varbinary(128) NOT NULL,
  `description` varbinary(128) DEFAULT NULL,
  `price` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> show create table `commerce`.`product`;
ERROR 1049 (42000): vtgate: http://morgox1:15001/: target: commerce.0.master, used tablet: zone1-100 (morgox1): vttablet: rpc error: code = InvalidArgument desc = Unknown database 'commerce' (errno 1049) (sqlstate 42000) (CallerID: userData1): Sql: "show create table `commerce`.`product`", BindVars: {}
mysql> show create table `vt_commerce`.`product`;
+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table   | Create Table                                                                                                                                                                                         |
+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| product | CREATE TABLE `product` (
  `sku` varbinary(128) NOT NULL,
  `description` varbinary(128) DEFAULT NULL,
  `price` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`sku`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |
+---------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by dkhenry** [comment]
This also appears to prevent Jira from working with Vitess 

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: vtgate: http://awesomeco-static-awsuseast1c-vtgate-aa4a8655-5df9d668f-7rdll:15000/: target: jira.-.master, used tablet: awsuseast1c-1629665228 (10.128.169.15): vttablet: rpc error: code = NotFound desc = Table 'jira.AO_0A5972_NOTIFICATION_SETTING' doesn't exist (errno 1146) (sqlstate 42S02) (CallerID: vtgate-static-user): Sql: "SHOW FULL COLUMNS FROM `AO_0A5972_NOTIFICATION_SETTING` FROM `jira` LIKE '%'", BindVars: {}
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2439)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1365)
	at com.mysql.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2442)
	at com.mysql.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2340)
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:50)
	at com.mysql.jdbc.DatabaseMetaData.getColumns(DatabaseMetaData.java:2338)
	at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:202)
	at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:202)
	at com.atlassian.pocketknife.internal.querydsl.schema.DefaultSchemaProvider.findColumnNames(DefaultSchemaProvider.java:176)
	at com.atlassian.pocketknife.internal.querydsl.schema.DefaultSchemaProvider.tableColumnNames(DefaultSchemaProvider.java:164)
	... 294 more
```

**Comment by dkhenry** [comment]
@saifalharthi

**Comment by morgo** [comment]
This has been verified as fixed.

**Comment by aquarapid** [comment]
For the record;  the fix for this seems to have fixed Sequel Pro as well (www.sequelpro.com)
