### ISSUE TITLE
Nodejs mysql driver causes ER_UNKNOWN_ERR on valid statement

### ISSUE THREAD

**Issue by dkhenry** [vitessio/vitess#5547]
#### Overview of the Issue
Using the mysql driver for Nodejs its possible to provide a valid query, but have vtgate reject it due to `unrecognized statement: ...`. 

#### Reproduction Steps
1. Install the nodejs mysql driver `npm install mysql`
1. Run the following script
```
var mysql = require('mysql')
var connection = mysql.createConnection({
	host: '127.0.0.1',
	user: 'user',
	password: 'password',
	database: 'main'
});

connection.connect();
connection.query('BEGIN;', function(error,results,fields){
	if(error) throw error;
	console.log('Success');
});

connection.end();
```

#### Binary version
```
Version: 8de7237f7 (Git branch 'master') built on Wed Nov  6 04:40:13 UTC 2019 by root@9665ea89c0d1 using go1.12.10 linux/amd64
```

#### Operating system and Environment details
using docker containers

#### Log Fragments
```
/home/dk/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error: ER_UNKNOWN_ERROR: vtgate: http://example-uswest1b-vtgate-e31295d8-f5ddc77d5-s89wk:15000/: unrecognized statement: BEGIN;
    at Query.Sequence._packetToError (/home/dk/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/dk/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/home/dk/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/dk/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/dk/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/dk/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/dk/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/home/dk/node_modules/mysql/lib/Connection.js:525:10)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    --------------------
    at Protocol._enqueue (/home/dk/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/dk/node_modules/mysql/lib/Connection.js:201:25)
    at Object.<anonymous> (/home/dk/src/ghost/ntest.js:10:12)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'ER_UNKNOWN_ERROR',
  errno: 1105,
  sqlMessage: 'vtgate: http://example-uswest1b-vtgate-e31295d8-f5ddc77d5-s89wk:15000/: unrecognized statement: BEGIN;',
  sqlState: 'HY000',
  index: 0,
  sql: 'BEGIN;'
}
```

**Comment by enisoc** [comment]
Does it work if you change the query from `BEGIN;` to `BEGIN`?

**Comment by saifalharthi** [comment]
@dkhenry was this issue fixed after merging https://github.com/vitessio/vitess/pull/5550 . If so we should close this issue

**Comment by dkhenry** [comment]
It was and we should
