### ISSUE TITLE
flaky unit_race test in go/vt/vttablet/tabletserver/vstreamer

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5623]
This might be a new race, I'm not sure:
```
ok  	vitess.io/vitess/go/vt/vttablet/tabletserver/txthrottler	1.034s
E1230 17:00:45.141275   18852 vstreamer.go:658] stream error @ e7e6a318-2b25-11ea-9df3-000d3a008aac:1-63: table t1 not found
panic: Fail in goroutine after TestInKeyRangeMultiColumn has completed

goroutine 322 [running]:
testing.(*common).Fail(0xc0001c6100)
	/opt/hostedtoolcache/go/1.12.14/x64/src/testing/testing.go:565 +0x1a4
testing.(*common).Error(0xc0001c6100, 0xc000457f88, 0x1, 0x1)
	/opt/hostedtoolcache/go/1.12.14/x64/src/testing/testing.go:654 +0x8b
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.startStream.func1(0xc0001ce720, 0x1381840, 0xc00024b600, 0xc0001c6100, 0xc0000a8780, 0x31, 0xc00024b640)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1154 +0x107
created by vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.startStream
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1151 +0xd5
FAIL	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer	6.720s
```

It occurred in this merge: https://github.com/vitessio/vitess/runs/368053318

It might have been introduced in https://github.com/vitessio/vitess/issues/5571 ?

**Comment by morgo** [comment]
I can see that there is #5622 open, which may address it? Feel free to close if that is the case.

**Comment by sougou** [comment]
Yeah. #5622 should fix this also.
