### ISSUE TITLE
 helm/vitess/templates/_vtctld.tpl: Removal of web_dir flags can break UI for older binaries

### ISSUE THREAD

**Issue by gedgar** [vitessio/vitess#5720]
Minikube version: v0.33.1
Helm version:
```
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

I ran into a few issues while trying to run through the Kubernetes tutorial:

1. When running `kvtctld.sh` (after making it executable, see #5719), my browser tries to open `http://192.168.39.142:31333/app2/` and I get a `404 page not found` error. 

2. Figuring this was related to #5597, I tried changing the images from `helm-1.0.7-5` -> `latest`, though after that all of my tablets were `CrashLoopBackOff`ing

Here are the vttablet + mysql logs:
**mysql**
```
+ '[' mysql56 = percona ']'
+ '[' mysql56 = mysql ']'
+ '[' mysql56 = mysql56 ']'
+ MYSQL_FLAVOR=MySQL56
+ export MYSQL_FLAVOR
++ cat
+++ cat /vtdataroot/tabletdata/tablet-uid
+ eval exec /vt/bin/mysqlctld -logtostderr=true -stderrthreshold=0 -tablet_dir '"tabletdata"' -tablet_uid '"794219800"' -socket_file '"/vtdataroot/mysqlctl.sock"' -init_db_sql_file '"/vt/config/init_db.sql"'
++ exec /vt/bin/mysqlctld -logtostderr=true -stderrthreshold=0 -tablet_dir tabletdata -tablet_uid 794219800 -socket_file /vtdataroot/mysqlctl.sock -init_db_sql_file /vt/config/init_db.sql
ERROR: logging before flag.Parse: E0116 01:00:01.306804       1 syslogger.go:122] can't connect to syslog
I0116 01:00:01.313152       1 mysqlctld.go:75] mycnf file (/vtdataroot/tabletdata/my.cnf) doesn't exist, initializing
I0116 01:00:01.313346       1 dbconfigs.go:303] DBConfigs: {
  "Conn": {
    "host": "",
    "port": 0,
    "uname": "vt_dba",
    "pass": "****",
    "dbname": "",
    "unix_socket": "/vtdataroot/tabletdata/mysql.sock",
    "charset": "utf8",
    "flags": 0,
    "ssl_ca": "",
    "ssl_ca_path": "",
    "ssl_cert": "",
    "ssl_key": "",
    "server_name": "",
    "DeprecatedDBName": "",
    "DisableClientDeprecateEOF": false+ '[' mysql56 = percona ']'
+ '[' mysql56 = mysql ']'
+ '[' mysql56 = mysql56 ']'
+ MYSQL_FLAVOR=MySQL56
+ export MYSQL_FLAVOR
++ cat
+++ cat /vtdataroot/tabletdata/tablet-uid
+++ hostname
+ eval exec /vt/bin/vttablet '-topo_implementation="etcd2"' '-topo_global_server_address="etcd-global-client.default:2379"' -topo_global_root=/vitess/global -logtostderr -port 15002 -grpc_port 16002 -service_map '"grpc-queryservice,grpc-tabletmanager,grpc-updatestream"' -tablet_dir '"tabletdata"' -tablet-path '"zone1-794219800"' -tablet_hostname '"zone1-commerce-0-rdonly-0.vttablet"' -init_keyspace '"commerce"' -init_shard '"0"' -init_tablet_type '"rdonly"' -health_check_interval '"5s"' -mysqlctl_socket '"/vtdataroot/mysqlctl.sock"' -enable_replication_reporter -init_db_name_override '"commerce"' '-app_pool_size="40"' '-dba_pool_size="20"' '-queryserver-config-max-result-size="10000"' '-queryserver-config-pool-size="24"' '-queryserver-config-query-timeout="30"' '-queryserver-config-stream-pool-size="100"' '-queryserver-config-transaction-cap="300"'
++ exec /vt/bin/vttablet -topo_implementation=etcd2 -topo_global_server_address=etcd-global-client.default:2379 -topo_global_root=/vitess/global -logtostderr -port 15002 -grpc_port 16002 -service_map grpc-queryservice,grpc-tabletmanager,grpc-updatestream -tablet_dir tabletdata -tablet-path zone1-794219800 -tablet_hostname zone1-commerce-0-rdonly-0.vttablet -init_keyspace commerce -init_shard 0 -init_tablet_type rdonly -health_check_interval 5s -mysqlctl_socket /vtdataroot/mysqlctl.sock -enable_replication_reporter -init_db_name_override commerce -app_pool_size=40 -dba_pool_size=20 -queryserver-config-max-result-size=10000 -queryserver-config-pool-size=24 -queryserver-config-query-timeout=30 -queryserver-config-stream-pool-size=100 -queryserver-config-transaction-cap=300
ERROR: logging before flag.Parse: E0116 01:00:01.532860       1 syslogger.go:122] can't connect to syslog
I0116 01:00:01.547362       1 streamlog.go:155] Streaming logs from TabletServer at /debug/querylog.
I0116 01:00:01.547384       1 streamlog.go:155] Streaming logs from TxLog at /debug/txlog.
I0116 01:00:01.547423       1 trace.go:151] successfully started tracing with [noop]
I0116 01:00:01.547510       1 mycnf_flag.go:123] No mycnf_server_id, no mycnf-file specified, using default config for server id 794219800: /vtdataroot/tabletdata/my.cnf
F0116 01:00:01.547538       1 vttablet.go:80] mycnf read failed: open /vtdataroot/tabletdata/my.cnf: no such file or directory
  },
  "Users": {
    "dba": "vt_dba"
  }
}
I0116 01:00:01.313582       1 mysqld.go:586] execCmd: /usr/sbin/mysqld /usr/sbin/mysqld [--version]
I0116 01:00:01.317302       1 mysqld.go:600] execCmd: /usr/sbin/mysqld output: /usr/sbin/mysqld  Ver 5.7.26-29 for Linux on x86_64 (Percona Server (GPL), Release 29, Revision 11ad961)
I0116 01:00:01.317342       1 mysqld.go:174] Using flavor: percona, version: {5 7 26}
I0116 01:00:01.317356       1 mysqld.go:639] mysqlctl.Init
I0116 01:00:01.317358       1 mysqld.go:621] mysqlctl.InitConfig
I0116 01:00:01.317362       1 mysqld.go:915] creating directory /vtdataroot/tabletdata
I0116 01:00:01.317378       1 mysqld.go:949] creating directory /vtdataroot/tabletdata/data
I0116 01:00:01.317385       1 mysqld.go:949] creating directory /vtdataroot/tabletdata/innodb
I0116 01:00:01.317390       1 mysqld.go:949] creating directory /vtdataroot/tabletdata/relay-logs
I0116 01:00:01.317396       1 mysqld.go:949] creating directory /vtdataroot/tabletdata/bin-logs
I0116 01:00:01.317401       1 mysqld.go:925] creating directory /vtdataroot/tabletdata/data
I0116 01:00:01.317404       1 mysqld.go:925] creating directory /vtdataroot/tabletdata/innodb/data
I0116 01:00:01.317408       1 mysqld.go:925] creating directory /vtdataroot/tabletdata/innodb/logs
I0116 01:00:01.317412       1 mysqld.go:925] creating directory /vtdataroot/tabletdata/tmp
I0116 01:00:01.317417       1 mysqld.go:925] creating directory /vtdataroot/tabletdata/relay-logs
I0116 01:00:01.317430       1 mysqld.go:925] creating directory /vtdataroot/tabletdata/bin-logs
I0116 01:00:01.317442       1 mysqld.go:781] make_mycnf hook doesn't exist, reading template files
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab6238]
goroutine 1 [running]:
vitess.io/vitess/go/exit.doRecover(0xc52120, 0x16978c0, 0x1697800)
	/vt/src/vitess.io/vitess/go/exit/exit.go:92 +0x1b8
vitess.io/vitess/go/exit.Recover()
	/vt/src/vitess.io/vitess/go/exit/exit.go:69 +0x48
panic(0xc52120, 0x16978c0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/GeertJohan/go%2erice.(*Box).IsEmbedded(...)
	/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.0/box.go:157
github.com/GeertJohan/go%2erice.(*Box).Open(0x0, 0xd8050f, 0x11, 0xc000399a08, 0x4f1262, 0xc00011e680)
	/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.0/box.go:185 +0x48
github.com/GeertJohan/go%2erice.(*Box).Bytes(0x0, 0xd8050f, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.0/box.go:280 +0x5c
vitess.io/vitess/go/vt/mysqlctl.(*Mysqld).getMycnfTemplate(0xc000131e30, 0x35, 0x0)
	/vt/src/vitess.io/vitess/go/vt/mysqlctl/mysqld.go:800 +0x9c
vitess.io/vitess/go/vt/mysqlctl.(*Mysqld).initConfig(0xc000131e30, 0xc0000f57a0, 0xc0000c2460, 0x1d, 0x0, 0xd7cea0)
	/vt/src/vitess.io/vitess/go/vt/mysqlctl/mysqld.go:782 +0x40c
vitess.io/vitess/go/vt/mysqlctl.(*Mysqld).InitConfig(0xc000131e30, 0xc0000f57a0, 0x0, 0x0)
	/vt/src/vitess.io/vitess/go/vt/mysqlctl/mysqld.go:628 +0x17f
vitess.io/vitess/go/vt/mysqlctl.(*Mysqld).Init(0xc000131e30, 0xeafe20, 0xc0000c6960, 0xc0000f57a0, 0x7ffe960b05ef, 0x16, 0x0, 0x0)
	/vt/src/vitess.io/vitess/go/vt/mysqlctl/mysqld.go:640 +0x89
main.main()
	/vt/src/vitess.io/vitess/go/cmd/mysqlctld/mysqlctld.go:85 +0x3d2
```

**vttablet**
```
+ '[' mysql56 = percona ']'
+ '[' mysql56 = mysql ']'
+ '[' mysql56 = mysql56 ']'
+ MYSQL_FLAVOR=MySQL56
+ export MYSQL_FLAVOR
++ cat
+++ cat /vtdataroot/tabletdata/tablet-uid
+++ hostname
+ eval exec /vt/bin/vttablet '-topo_implementation="etcd2"' '-topo_global_server_address="etcd-global-client.default:2379"' -topo_global_root=/vitess/global -logtostderr -port 15002 -grpc_port 16002 -service_map '"grpc-queryservice,grpc-tabletmanager,grpc-updatestream"' -tablet_dir '"tabletdata"' -tablet-path '"zone1-794219800"' -tablet_hostname '"zone1-commerce-0-rdonly-0.vttablet"' -init_keyspace '"commerce"' -init_shard '"0"' -init_tablet_type '"rdonly"' -health_check_interval '"5s"' -mysqlctl_socket '"/vtdataroot/mysqlctl.sock"' -enable_replication_reporter -init_db_name_override '"commerce"' '-app_pool_size="40"' '-dba_pool_size="20"' '-queryserver-config-max-result-size="10000"' '-queryserver-config-pool-size="24"' '-queryserver-config-query-timeout="30"' '-queryserver-config-stream-pool-size="100"' '-queryserver-config-transaction-cap="300"'
++ exec /vt/bin/vttablet -topo_implementation=etcd2 -topo_global_server_address=etcd-global-client.default:2379 -topo_global_root=/vitess/global -logtostderr -port 15002 -grpc_port 16002 -service_map grpc-queryservice,grpc-tabletmanager,grpc-updatestream -tablet_dir tabletdata -tablet-path zone1-794219800 -tablet_hostname zone1-commerce-0-rdonly-0.vttablet -init_keyspace commerce -init_shard 0 -init_tablet_type rdonly -health_check_interval 5s -mysqlctl_socket /vtdataroot/mysqlctl.sock -enable_replication_reporter -init_db_name_override commerce -app_pool_size=40 -dba_pool_size=20 -queryserver-config-max-result-size=10000 -queryserver-config-pool-size=24 -queryserver-config-query-timeout=30 -queryserver-config-stream-pool-size=100 -queryserver-config-transaction-cap=300
ERROR: logging before flag.Parse: E0116 01:00:01.532860       1 syslogger.go:122] can't connect to syslog
I0116 01:00:01.547362       1 streamlog.go:155] Streaming logs from TabletServer at /debug/querylog.
I0116 01:00:01.547384       1 streamlog.go:155] Streaming logs from TxLog at /debug/txlog.
I0116 01:00:01.547423       1 trace.go:151] successfully started tracing with [noop]
I0116 01:00:01.547510       1 mycnf_flag.go:123] No mycnf_server_id, no mycnf-file specified, using default config for server id 794219800: /vtdataroot/tabletdata/my.cnf
F0116 01:00:01.547538       1 vttablet.go:80] mycnf read failed: open /vtdataroot/tabletdata/my.cnf: no such file or directory
```

**Comment by morgo** [comment]
This looks like the bug fixed in https://github.com/vitessio/vitess/pull/5711

We may need to push new images to fix. @derekperkins do you mind applying a second set of eyes?

**Comment by derekperkins** [comment]
We're currently running helm-1.0.7-6, and used helm-1.0.7-5 and all the tagged releases prior. I definitely wouldn't use latest. It changes all the time randomly (meaning not always moving forward) based on Docker Hub's build scheduler, and could break. None of the tagged images have embedded assets, so any errors you're seeing aren't related to that.

Without seeing any logs from your first attempt, my best guess is that you've got a port mismatch or something similar. Did you ever see all your pods up and healthy?

**Comment by enisoc** [comment]
> When running kvtctld.sh (after making it executable, see #5719), my browser tries to open http://192.168.39.142:31333/app2/ and I get a 404 page not found error.

The vtctld 2.0 UI recently moved from `/app2/` to `/app/`, although I would have expected you'd be redirected automatically.

The crash when you switched to `:latest` looks like the one that was fixed by #5711. My guess is perhaps the `:latest` tag for this image repo doesn't have the latest binary. There's a known problem where these images contain old binaries because Docker Hub long ago silently removed a feature we had been relying on to prevent that. I fixed that for `vitess/lite`, but not for the other "derived" images.

**Comment by gedgar** [comment]
Attempting to run `latest` was admittedly a shot in the dark. 

@derekperkins, all pods look healthy:

```
NAME                                       READY   STATUS      RESTARTS   AGE
commerce-apply-schema-initial-qzx7f        0/1     Completed   0          54m
commerce-apply-vschema-initial-sgjrm       0/1     Completed   0          54m
etcd-global-vtpqcltdsv                     1/1     Running     0          54m
etcd-operator-85f7494fcf-4q8hp             1/1     Running     0          56m
etcd-zone1-w4k6clbrvh                      1/1     Running     0          54m
vtctld-5794f66c69-kjzxb                    1/1     Running     2          54m
vtgate-zone1-6fc7fcd967-82p95              1/1     Running     2          54m
zone1-commerce-0-init-shard-master-czrbt   0/1     Completed   0          54m
zone1-commerce-0-rdonly-0                  6/6     Running     0          54m
zone1-commerce-0-replica-0                 6/6     Running     0          54m
zone1-commerce-0-replica-1                 6/6     Running     0          54m
```

FWIW, I'm able to port-forward the `grpc_port` locally just fine:
`minictl port-forward po/vtctld-5794f66c69-kjzxb 15999:15999 &`
```
vtctlclient -server :15999 ListAllTablets
Handling connection for 15999
zone1-0794219800 commerce 0 rdonly zone1-commerce-0-rdonly-0.vttablet:15002 zone1-commerce-0-rdonly-0.vttablet:3306 []
zone1-1564760600 commerce 0 master zone1-commerce-0-replica-0.vttablet:15002 zone1-commerce-0-replica-0.vttablet:3306 []
zone1-1564760601 commerce 0 replica zone1-commerce-0-replica-1.vttablet:15002 zone1-commerce-0-replica-1.vttablet:3306 []
```

However, attempts to forward the web port locally redirect me to `localhost:15000/web2/ ` and the `404 page not found` error, which is the same issue I had when running `kvtctld.sh` and hitting up the IP:Port returned by `minikube service vtctld --url|head -n 1` 

Confirmed that the binaries are pretty old on `helm-1.0.7.5` and shouldn't have the changes from #5597 :
```
Version: 92f7d546f (Git branch 'master') built on Sun Nov  3 21:15:08 UTC 2019 by root@20dc394ae80b using go1.12.10 linux/amd64
```

However, it looks like we're not setting the `web_dir` flags for `vtctld`:

```
      eval exec /vt/bin/vtctld $(cat <<END_OF_COMMAND
        -cell="zone1"
        -workflow_manager_init
        -workflow_manager_use_election
        -logtostderr=true
        -stderrthreshold=0
        -port=15000
        -grpc_port=15999
        -service_map="grpc-vtctl"
        -topo_implementation="etcd2"
        -topo_global_server_address="etcd-global-client.default:2379"
        -topo_global_root=/vitess/global
        
        
          
        
        
        
      END_OF_COMMAND
      )
```

**Comment by enisoc** [comment]
For the latest binaries from master, the `web_dir*` flags are gone and must not be set or else the binary will crash. It seems like what happened is the images have the new, correct flag behavior (don't set `web_dir*`), but those same images have the old binaries (due to the Docker Hub issue mentioned above) that still expect `web_dir*` to be set.

If this diagnosis is correct, the fix is to find images that eventually did pick up the correct binaries and tag those with a new version number, then update the helm charts to use that new tag. I don't know how our helm release process works exactly so I'll defer to @derekperkins to do that if he agrees with the solution.

**Comment by gedgar** [comment]
To clarify, it looks like `vtctld`'s flag behavior is defined in `helm/vitess/templates/_vtctld.tpl`, which was recently changed in [this commit](https://github.com/vitessio/vitess/commit/0882f189b3affa3ab40d8a7c06cb3e3c1bfa5a7b).

Testing `helm-1.0.7.6`, it looks like the binaries are still a bit too old:
```
Version: 1dc91505e (Git branch 'master') built on Mon Dec 23 10:41:56 UTC 2019 by root@142d4907ebb9 using go1.12.14 linux/amd64
```

**Comment by derekperkins** [comment]
Ah, I wasn't aware that somebody had already merged code deleting those flags. I thought we were still safely behind all these recent breaking changes and I wasn't planning on doing a new release until that had all been figured out.

Really we should probably push a helm v2.0 release that only works with >= Vitess 5.0. I think we should revert those `vtctld.tpl` changes and coincide the two breaking change releases.
