### ISSUE TITLE
MariaDB JDBC Connector fails to connect to vtgate with default options 

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#5851]
Scenario:
  Use the MariaDB JDBC connector (tested versions 2.1.2 and 2.5.4) and it will by default send the following command to vtgate at connection time:

```
set autocommit=1, sql_mode = concat(@@sql_mode,',STRICT_TRANS_TABLES'
```

Which will fail on the vtgate side with:

```
invalid syntax: concat(@@sql_mode, ',STRICT_TRANS_TABLES')
```

As a result, the JDBC app will fail to connect with a stack trace like:

```
java.sql.SQLException: vtgate: http://localhost:15001/: invalid syntax: concat(@@sql_mode, ',STRICT_TRANS_TABLES')
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1598)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1460)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1423)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.additionalData(AbstractConnectProtocol.java:998)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.postConnectionQueries(AbstractConnectProtocol.java:800)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:549)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1238)
```

You can work around this problem by preventing the MariaDB connector from sending the `concat(@@sql_mode, ',STRICT_TRANS_TABLES')` statement by using the JDBC connection string option `jdbcCompliantTruncation=false`.  This workaround should be safe in most cases, since MySQL 5.7 and MariaDB 10.2.4 onwards both default to including STRICT_TRANS_TABLES in the default sql_mode.

The core issue of the error is that we do not support functions in `set` statements, even the ones we essentially ignore.

**Comment by harshit-gangal** [comment]
Fixed by #6459
