### ISSUE TITLE
unit race: flaky test

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#5929]
```
--- FAIL: TestParallelRunnerApprovalFirstRunningSecondRunning (0.00s)
panic: close of closed channel [recovered]
	panic: close of closed channel

goroutine 84 [running]:
testing.tRunner.func1(0xc000288400)
	/opt/hostedtoolcache/go/1.13.8/x64/src/testing/testing.go:874 +0x69f
panic(0xe7ad60, 0x10a0960)
	/opt/hostedtoolcache/go/1.13.8/x64/src/runtime/panic.go:679 +0x1b2
vitess.io/vitess/go/vt/workflow.TestParallelRunnerApprovalFirstRunningSecondRunning(0xc000288400)
	/home/runner/work/vitess/vitess/go/vt/workflow/parallel_runner_test.go:363 +0xa09
testing.tRunner(0xc000288400, 0xfa19b8)
	/opt/hostedtoolcache/go/1.13.8/x64/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.13.8/x64/src/testing/testing.go:960 +0x652
FAIL	vitess.io/vitess/go/vt/workflow	0.061s
```

**Comment by deepthi** [comment]
duplicates #4324
