### ISSUE TITLE
Data race in unit test

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#5970]
The crash didn't show which test:

```
==================
WARNING: DATA RACE
Read at 0x00c000180250 by goroutine 138:
  vitess.io/vitess/go/vt/discovery.(*healthCheckConn).stream()
      /home/runner/work/vitess/vitess/go/vt/vttablet/tabletconn/tablet_conn.go:64 +0x4b5
  vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).checkConn()
      /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:545 +0x496

Previous write at 0x00c000180250 by goroutine 339:
  [failed to restore the stack]

Goroutine 138 (running) created at:
  vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).AddTablet()
      /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:769 +0x595
  vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).loadTablets()
      /home/runner/work/vitess/vitess/go/vt/discovery/topology_watcher.go:259 +0xd87
  vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).watch()
      /home/runner/work/vitess/vitess/go/vt/discovery/topology_watcher.go:168 +0xfc

Goroutine 339 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:909 +0x199
  testing.runTests()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:218 +0x223
==================
==================
WARNING: DATA RACE
Read at 0x000002395178 by goroutine 138:
  vitess.io/vitess/go/vt/wrangler.init.1.func1()
      /home/runner/work/vitess/vitess/go/vt/wrangler/vdiff_env_test.go:69 +0x54
  vitess.io/vitess/go/vt/discovery.(*healthCheckConn).stream()
      /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:614 +0x55f
  vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).checkConn()
      /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:545 +0x496

Previous write at 0x000002395178 by goroutine 339:
  vitess.io/vitess/go/vt/wrangler.newTestVDiffEnv()
      /home/runner/work/vitess/vitess/go/vt/wrangler/vdiff_env_test.go:166 +0x1671
  vitess.io/vitess/go/vt/wrangler.TestVDiffDefaults()
      /home/runner/work/vitess/vitess/go/vt/wrangler/vdiff_test.go:824 +0xd1
  testing.tRunner()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:909 +0x199
      /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:769 +0x595
  vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).loadTablets()
      /home/runner/work/vitess/vitess/go/vt/discovery/topology_watcher.go:259 +0xd87
  vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).watch()
      /home/runner/work/vitess/vitess/go/vt/discovery/topology_watcher.go:168 +0xfc

Goroutine 339 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:909 +0x199
  testing.runTests()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:218 +0x223
==================
==================
WARNING: DATA RACE
Write at 0x00c00078a4f0 by goroutine 138:
  sync/atomic.CompareAndSwapInt32()
      /opt/hostedtoolcache/go/1.13.9/x64/src/runtime/race_amd64.s:293 +0xb
  sync.(*Mutex).Lock()
      /opt/hostedtoolcache/go/1.13.9/x64/src/sync/mutex.go:74 +0x49
  vitess.io/vitess/go/vt/wrangler.init.1.func1()
      /home/runner/work/vitess/vitess/go/vt/wrangler/vdiff_env_test.go:69 +0x6a
  vitess.io/vitess/go/vt/discovery.(*healthCheckConn).stream()
      /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:614 +0x55f
  vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).checkConn()
      /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:545 +0x496

Previous write at 0x00c00078a4f0 by goroutine 339:
  [failed to restore the stack]

Goroutine 138 (running) created at:
  vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).AddTablet()
      /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:769 +0x595
  vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).loadTablets()
      /home/runner/work/vitess/vitess/go/vt/discovery/topology_watcher.go:259 +0xd87
  vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).watch()
      /home/runner/work/vitess/vitess/go/vt/discovery/topology_watcher.go:168 +0xfc

Goroutine 339 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:960 +0x651
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1202 +0xa6
  testing.tRunner()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:909 +0x199
  testing.runTests()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1200 +0x521
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1117 +0x2ff
  main.main()
      _testmain.go:218 +0x223
==================
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x143e7d6]

goroutine 2570 [running]:
vitess.io/vitess/go/vt/wrangler.(*testVDiffTablet).Close(0x0, 0x197cec0, 0xc00075fb60, 0x197cec0, 0xc00075fb60)
	<autogenerated>:1 +0x46
vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).finalizeConn(0xc0002ff7a0, 0xc00021df40)
	/home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:500 +0x2c0
panic(0x1579ac0, 0x237cf80)
	/opt/hostedtoolcache/go/1.13.9/x64/src/runtime/panic.go:679 +0x1b2
vitess.io/vitess/go/vt/wrangler.(*testVDiffTablet).StreamHealth(0x0, 0x197ce40, 0xc000771d80, 0xc000c8eae0, 0x0, 0x0)
	/home/runner/work/vitess/vitess/go/vt/wrangler/vdiff_env_test.go:232 +0x108
vitess.io/vitess/go/vt/discovery.(*healthCheckConn).stream(0xc00021df40, 0x197ce40, 0xc000771d80, 0xc0002ff7a0, 0xc000c8eae0)
	/home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:623 +0xc7
vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).checkConn(0xc0002ff7a0, 0xc00021df40, 0xc00046f170, 0x10)
	/home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:545 +0x497
created by vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).AddTablet
	/home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:769 +0x596
FAIL	vitess.io/vitess/go/vt/wrangler	5.974s
ok  	vitess.io/vitess/go/vt/zkctl	5.287s
FAIL
```

**Comment by deepthi** [comment]
Should we add `-v` to unit_test_runner.sh? Then we will know which test is failing (next time).

**Comment by sougou** [comment]
The PR from @rohit-nayak-ps #5949 exposed this flakiness, and he's fixing it in that PR.
FTR, the failure was in the wrangler unit test.

**Comment by deepthi** [comment]
@rohit-nayak-ps looks like this may have been fixed?
