### ISSUE TITLE
Flakyness: Fail in goroutine after TestInKeyRangeMultiColumn has completed

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#6340]
```
E0618 02:13:45.507820   28914 vstreamer.go:796] stream error @ 0-1639850837-122: table t1 not found
panic: Fail in goroutine after TestInKeyRangeMultiColumn has completed

goroutine 521 [running]:
testing.(*common).Fail(0xc0000cb700)
	/opt/hostedtoolcache/go/1.13.12/x64/src/testing/testing.go:609 +0x151
testing.(*common).Errorf(0xc0000cb700, 0xf4e0b3, 0x3, 0xc00030ba00, 0x1, 0x1)
	/opt/hostedtoolcache/go/1.13.12/x64/src/testing/testing.go:704 +0x90
github.com/stretchr/testify/assert.Fail(0x10bba00, 0xc0000cb700, 0xc00028e2a0, 0x63, 0x0, 0x0, 0x0, 0xf29540)
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.4.0/assert/assertions.go:261 +0x2b3
github.com/stretchr/testify/assert.Nil(0x10bba00, 0xc0000cb700, 0xde48a0, 0xc00030b870, 0x0, 0x0, 0x0, 0xc000286a00)
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.4.0/assert/assertions.go:497 +0x12f
github.com/stretchr/testify/require.Nil(0x10c5380, 0xc0000cb700, 0xde48a0, 0xc00030b870, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.4.0/require/require.go:942 +0xcb
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.startStream.func1(0xc0001ab740, 0x10d7660, 0xc0005badc0, 0xc0000cb700, 0xc0004087a0, 0x18, 0x0, 0x0, 0x0, 0xc0005bae00)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1649 +0x147
created by vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.startStream
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1645 +0x111
FAIL	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer	11.446s
```

**Comment by rohit-nayak-ps** [comment]
Fixed by https://github.com/vitessio/vitess/pull/6341
