### ISSUE TITLE
flaky vstreamer test

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6538]
https://github.com/vitessio/vitess/runs/950239718?check_suite_focus=true

```
E1015 19:29:26.003610   31421 vstreamer_test.go:1776] [begin insert into stream1 values (2, 'bbb') insert into stream2 values (1, 'aaa') update stream1 set val='ccc' delete from stream1 commit] (1): event:
"type:FIELD field_event:<table_name:\"stream1\" fields:<name:\"id\" type:INT32 table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"id\" column_length:11 charset:63 > fields:<name:\"val\" type:VARBINARY table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"val\" column_length:128 charset:63 > > ", want
"type:FIELD field_event:<table_name:\"stream1\" fields:<name:\"id\" type:INT32 table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"id\" column_length:11 charset:63 > fields:<name:\"val\" type:VARBINARY table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"val\" column_length:256 charset:63 > > "
panic: test timed out after 10m0s

goroutine 596 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:1377 +0xdf
created by time.goFunc
	/opt/hostedtoolcache/go/1.13.15/x64/src/time/sleep.go:168 +0x44

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00037ae00, 0xf07d77, 0xe, 0xf608c0, 0x4c2201)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:961 +0x377
testing.runTests.func1(0xc00037a100)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:1202 +0x78
testing.tRunner(0xc00037a100, 0xc00029fca0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:909 +0xc9
testing.runTests(0xc00000e9a0, 0x1897960, 0x2e, 0x2e, 0x0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:1200 +0x2a7
testing.(*M).Run(0xc0001def80, 0x0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:1117 +0x176
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.TestMain.func1(0xc0001def80, 0x0)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/main_test.go:60 +0x239
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.TestMain(0xc0001def80)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/main_test.go:61 +0xa4
main.main()
	_testmain.go:132 +0x135

goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x18a8380)
	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x26f

goroutine 20 [syscall, 9 minutes]:
os/signal.signal_recv(0x0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/opt/hostedtoolcache/go/1.13.15/x64/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/opt/hostedtoolcache/go/1.13.15/x64/src/os/signal/signal_unix.go:29 +0x41

goroutine 35 [chan receive, 9 minutes]:
vitess.io/vitess/go/vt/dbconfigs.init.0.func1(0xc0001b8060)
	/home/runner/work/vitess/vitess/go/vt/dbconfigs/credentials.go:136 +0x41
created by vitess.io/vitess/go/vt/dbconfigs.init.0
	/home/runner/work/vitess/vitess/go/vt/dbconfigs/credentials.go:135 +0x11b

goroutine 267 [chan receive, 9 minutes]:
vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema.func1(0xefdca0, 0x5, 0xc000293770, 0x10838e0, 0xc0000ba018, 0xc00019c990, 0xc0001d6470)
	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:562 +0x2b9
created by vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema
	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:540 +0xb1

goroutine 11 [chan receive, 9 minutes]:
vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema.func1(0xc000080c00, 0xc000080ae0, 0xc0000329f0)
	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:72 +0xbb
created by vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema
	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:69 +0x356

goroutine 49 [chan receive]:
vitess.io/vitess/go/stats.(*Rates).track(0xc0002f07e0)
	/home/runner/work/vitess/vitess/go/stats/rates.go:99 +0x57
created by vitess.io/vitess/go/stats.NewRates
	/home/runner/work/vitess/vitess/go/stats/rates.go:91 +0x1c1

goroutine 10 [chan receive, 9 minutes]:
vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema.func1(0xefdca0, 0x5, 0xc000293770, 0x10838e0, 0xc0000ba018, 0xc000044670, 0xc00003c440)
	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:562 +0x2b9
created by vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema
	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:540 +0xb1

goroutine 50 [select]:
vitess.io/vitess/go/timer.(*Timer).run(0xc0003109a0, 0xc0002eeb30)
	/home/runner/work/vitess/vitess/go/timer/timer.go:98 +0xc4
created by vitess.io/vitess/go/timer.(*Timer).Start
	/home/runner/work/vitess/vitess/go/timer/timer.go:86 +0xb2

goroutine 51 [select]:
vitess.io/vitess/go/timer.(*Timer).run(0xc000310c40, 0xc0002eed50)
	/home/runner/work/vitess/vitess/go/timer/timer.go:98 +0xc4
created by vitess.io/vitess/go/timer.(*Timer).Start
	/home/runner/work/vitess/vitess/go/timer/timer.go:86 +0xb2

goroutine 398 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc0003cd708)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc0003cd700)
	/opt/hostedtoolcache/go/1.13.15/x64/src/sync/waitgroup.go:130 +0x64
runtime.Goexit()
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:563 +0xec
testing.(*common).FailNow(0xc00037ae00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:653 +0x39
testing.(*common).Fatalf(0xc00037ae00, 0xf16210, 0x1b, 0xc0000fda28, 0x4, 0x4)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:716 +0x90
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.expectLog(0x10838a0, 0xc00007fec0, 0xc00037ae00, 0xd3f460, 0xc0004b64c0, 0xc0004a27e0, 0xc0004b64e0, 0x1, 0x1)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1777 +0xaa5
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.runCases(0xc00037ae00, 0x0, 0xc0000fde70, 0x6, 0x6, 0xf006b4, 0x7, 0x0, 0x0, 0x0)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1699 +0x3aa
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.TestStatements(0xc00037ae00)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:645 +0x6d1
testing.tRunner(0xc00037ae00, 0xf608c0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:960 +0x350

goroutine 53 [select]:
vitess.io/vitess/go/timer.(*Timer).run(0xc000310e20, 0xc0002eef10)
	/home/runner/work/vitess/vitess/go/timer/timer.go:98 +0xc4
created by vitess.io/vitess/go/timer.(*Timer).Start
	/home/runner/work/vitess/vitess/go/timer/timer.go:86 +0xb2

goroutine 54 [select]:
vitess.io/vitess/go/timer.(*Timer).run(0xc000310e40, 0xc0002eef50)
	/home/runner/work/vitess/vitess/go/timer/timer.go:98 +0xc4
created by vitess.io/vitess/go/timer.(*Timer).Start
	/home/runner/work/vitess/vitess/go/timer/timer.go:86 +0xb2

goroutine 6 [select, 9 minutes]:
vitess.io/vitess/go/timer.(*Timer).run(0xc000310da0, 0xc00000e260)
	/home/runner/work/vitess/vitess/go/timer/timer.go:98 +0xc4
created by vitess.io/vitess/go/timer.(*Timer).Start
	/home/runner/work/vitess/vitess/go/timer/timer.go:86 +0xb2

goroutine 129 [chan receive, 9 minutes]:
vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema.func1(0xefdca0, 0x5, 0xc000293770, 0x10838e0, 0xc0000ba018, 0xc0002ef230, 0xc0001d78d0)
	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:562 +0x2b9
created by vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema
	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:540 +0xb1

goroutine 268 [chan receive, 9 minutes]:
vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema.func1(0xc000080780, 0xc0000806c0, 0xc0003363c0)
	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:72 +0xbb
created by vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema
	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:69 +0x356

goroutine 408 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f91ef179ea8, 0x72, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00014f798, 0x72, 0x4000, 0x4000, 0xffffffffffffffff)
	/opt/hostedtoolcache/go/1.13.15/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.13.15/x64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00014f780, 0xc0004e0000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc00014f780, 0xc0004e0000, 0x4000, 0x4000, 0x22b, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000bf198, 0xc0004e0000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/net.go:184 +0x68
bufio.(*Reader).Read(0xc0000c0d80, 0xc00050a400, 0x4, 0x4, 0xc00048ec08, 0x40e8b8, 0x10)
	/opt/hostedtoolcache/go/1.13.15/x64/src/bufio/bufio.go:226 +0x26a
io.ReadAtLeast(0x1066940, 0xc0000c0d80, 0xc00050a400, 0x4, 0x4, 0x4, 0xc0000c0d80, 0xc0005809a0, 0x20)
	/opt/hostedtoolcache/go/1.13.15/x64/src/io/io.go:310 +0x87
io.ReadFull(...)
	/opt/hostedtoolcache/go/1.13.15/x64/src/io/io.go:329
vitess.io/vitess/go/mysql.(*Conn).readHeaderFrom(0xc000391590, 0x1066940, 0xc0000c0d80, 0x20, 0x20, 0x20)
	/home/runner/work/vitess/vitess/go/mysql/conn.go:322 +0x87
vitess.io/vitess/go/mysql.(*Conn).readOnePacket(0xc000391590, 0xc00048ede8, 0x40e046, 0xc0004c6440, 0xc00048ed90, 0xc00048ed90)
	/home/runner/work/vitess/vitess/go/mysql/conn.go:461 +0x6b
vitess.io/vitess/go/mysql.(*Conn).readPacket(0xc000391590, 0x2, 0x2000000000020, 0x0, 0x1, 0xc00048ee18)
	/home/runner/work/vitess/vitess/go/mysql/conn.go:483 +0x32
vitess.io/vitess/go/mysql.(*Conn).ReadPacket(0xc000391590, 0xc00048eefc, 0xc0003e4600, 0xc00048ef60, 0xc0004a2cc0, 0xc0004a2c60)
	/home/runner/work/vitess/vitess/go/mysql/conn.go:519 +0x2f
vitess.io/vitess/go/mysql.mariadbFlavor.readBinlogEvent(0xc000391590, 0x1098ee0, 0xc0004c6440, 0xc000486150, 0x0)
	/home/runner/work/vitess/vitess/go/mysql/flavor_mariadb.go:213 +0x2f
vitess.io/vitess/go/mysql.(*Conn).ReadBinlogEvent(...)
	/home/runner/work/vitess/vitess/go/mysql/flavor.go:223
vitess.io/vitess/go/vt/binlog.(*BinlogConnection).streamEvents.func1(0xc0004a2c60, 0xc000380420, 0x10838a0, 0xc000486140)
	/home/runner/work/vitess/vitess/go/vt/binlog/binlog_connection.go:139 +0xa2
created by vitess.io/vitess/go/vt/binlog.(*BinlogConnection).streamEvents
	/home/runner/work/vitess/vitess/go/vt/binlog/binlog_connection.go:133 +0xa1

goroutine 146 [chan receive, 9 minutes]:
vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema.func1(0xc0001ea420, 0xc0001ea3c0, 0xc0003b68d0)
	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:72 +0xbb
created by vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema
	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:69 +0x356

goroutine 401 [select, 9 minutes]:
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.vstream.func1(0xc0000107e0, 0x1, 0x1, 0xc0004fb918, 0xc0000107e0)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1816 +0x1a5
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.newUVStreamer.func1(0xc0000107e0, 0x1, 0x1, 0x0, 0x1)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go:99 +0x6b
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*vstreamer).parseEvents.func1(0xc000502510, 0xc000502510, 0x18a7e00)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:222 +0x3b1
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*vstreamer).parseEvents(0xc000384a80, 0x10838a0, 0xc000486040, 0xc0004a2c60, 0x0, 0x0)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:309 +0x70f
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*vstreamer).replicate(0xc000384a80, 0x10838e0, 0xc0000ba010, 0x0, 0x0)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:180 +0x1a7
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*vstreamer).Stream(0xc000384a80, 0x0, 0x0)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:159 +0x1c0
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*uvstreamer).Stream(0xc0000e5e60, 0x10838a0, 0xc00007fec0)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go:377 +0x216
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*Engine).Stream(0xc00037a000, 0x10838a0, 0xc00007fec0, 0xf006b4, 0x7, 0x0, 0x0, 0x0, 0xc00007ff00, 0xc000380210, ...)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/engine.go:216 +0x166
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.vstream(0x10838a0, 0xc00007fec0, 0xc00037ae00, 0xf006b4, 0x7, 0x0, 0x0, 0x0, 0xc00007ff00, 0xc0004a27e0, ...)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1814 +0x10d
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.startStream.func1(0xc0004a27e0, 0xc0003cd700, 0x10838a0, 0xc00007fec0, 0xc00037ae00, 0xf006b4, 0x7, 0x0, 0x0, 0x0, ...)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1800 +0x163
created by vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.startStream
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1796 +0x156
FAIL	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer	602.878s
```

**Comment by rohit-nayak-ps** [comment]
this has been fixed
