### ISSUE TITLE
Vstreamer unit test failing

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#6693]
```
2020-09-10T11:05:52.1072094Z panic: test timed out after 10m0s
2020-09-10T11:05:52.1072201Z 
2020-09-10T11:05:52.1072553Z goroutine 573 [running]:
2020-09-10T11:05:52.1072719Z testing.(*M).startAlarm.func1()
2020-09-10T11:05:52.1073001Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:1377 +0xdf
2020-09-10T11:05:52.1073219Z created by time.goFunc
2020-09-10T11:05:52.1073408Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/time/sleep.go:168 +0x44
2020-09-10T11:05:52.1073483Z 
2020-09-10T11:05:52.1073686Z goroutine 1 [chan receive, 9 minutes]:
2020-09-10T11:05:52.1074205Z testing.(*T).Run(0xc0000bb400, 0xefeecc, 0xe, 0xf56c30, 0x4c2201)
2020-09-10T11:05:52.1074514Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:961 +0x377
2020-09-10T11:05:52.1075152Z testing.runTests.func1(0xc0001f7400)
2020-09-10T11:05:52.1075478Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:1202 +0x78
2020-09-10T11:05:52.1075798Z testing.tRunner(0xc0001f7400, 0xc0002d5ca0)
2020-09-10T11:05:52.1076170Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:909 +0xc9
2020-09-10T11:05:52.1076463Z testing.runTests(0xc00036b2e0, 0x1883120, 0x2c, 0x2c, 0x0)
2020-09-10T11:05:52.1076728Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:1200 +0x2a7
2020-09-10T11:05:52.1076956Z testing.(*M).Run(0xc000256600, 0x0)
2020-09-10T11:05:52.1077150Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:1117 +0x176
2020-09-10T11:05:52.1077426Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.TestMain.func1(0xc000256600, 0x0)
2020-09-10T11:05:52.1077727Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/main_test.go:60 +0x239
2020-09-10T11:05:52.1077944Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.TestMain(0xc000256600)
2020-09-10T11:05:52.1078153Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/main_test.go:61 +0xa4
2020-09-10T11:05:52.1078362Z main.main()
2020-09-10T11:05:52.1078504Z 	_testmain.go:128 +0x135
2020-09-10T11:05:52.1078668Z 
2020-09-10T11:05:52.1081732Z goroutine 6 [chan receive]:
2020-09-10T11:05:52.1082064Z github.com/golang/glog.(*loggingT).flushDaemon(0x1893e80)
2020-09-10T11:05:52.1083069Z 	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
2020-09-10T11:05:52.1083365Z created by github.com/golang/glog.init.0
2020-09-10T11:05:52.1083839Z 	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x26f
2020-09-10T11:05:52.1084022Z 
2020-09-10T11:05:52.1084186Z goroutine 7 [syscall, 9 minutes]:
2020-09-10T11:05:52.1084319Z os/signal.signal_recv(0x0)
2020-09-10T11:05:52.1084489Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/sigqueue.go:147 +0x9c
2020-09-10T11:05:52.1084706Z os/signal.loop()
2020-09-10T11:05:52.1084898Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/os/signal/signal_unix.go:23 +0x22
2020-09-10T11:05:52.1085033Z created by os/signal.init.0
2020-09-10T11:05:52.1085287Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/os/signal/signal_unix.go:29 +0x41
2020-09-10T11:05:52.1085523Z 
2020-09-10T11:05:52.1085785Z goroutine 24 [chan receive, 9 minutes]:
2020-09-10T11:05:52.1085965Z vitess.io/vitess/go/vt/dbconfigs.init.0.func1(0xc0001dade0)
2020-09-10T11:05:52.1086229Z 	/home/runner/work/vitess/vitess/go/vt/dbconfigs/credentials.go:136 +0x41
2020-09-10T11:05:52.1086469Z created by vitess.io/vitess/go/vt/dbconfigs.init.0
2020-09-10T11:05:52.1086664Z 	/home/runner/work/vitess/vitess/go/vt/dbconfigs/credentials.go:135 +0x11b
2020-09-10T11:05:52.1086798Z 
2020-09-10T11:05:52.1086953Z goroutine 263 [chan receive, 9 minutes]:
2020-09-10T11:05:52.1087303Z vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema.func1(0xef4e74, 0x5, 0xc0003323c0, 0x1078620, 0xc00003c0d8, 0xc000421bf0, 0xc0003d3bf0)
2020-09-10T11:05:52.1087596Z 	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:562 +0x2b9
2020-09-10T11:05:52.1087896Z created by vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema
2020-09-10T11:05:52.1088166Z 	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:540 +0xb1
2020-09-10T11:05:52.1088323Z 
2020-09-10T11:05:52.1088461Z goroutine 39 [select]:
2020-09-10T11:05:52.1088644Z vitess.io/vitess/go/timer.(*Timer).run(0xc00036a900, 0xc00036c830)
2020-09-10T11:05:52.1088872Z 	/home/runner/work/vitess/vitess/go/timer/timer.go:98 +0xc4
2020-09-10T11:05:52.1089050Z created by vitess.io/vitess/go/timer.(*Timer).Start
2020-09-10T11:05:52.1089293Z 	/home/runner/work/vitess/vitess/go/timer/timer.go:86 +0xb2
2020-09-10T11:05:52.1089443Z 
2020-09-10T11:05:52.1089781Z goroutine 37 [chan receive]:
2020-09-10T11:05:52.1089957Z vitess.io/vitess/go/stats.(*Rates).track(0xc000330c60)
2020-09-10T11:05:52.1090200Z 	/home/runner/work/vitess/vitess/go/stats/rates.go:99 +0x57
2020-09-10T11:05:52.1090368Z created by vitess.io/vitess/go/stats.NewRates
2020-09-10T11:05:52.1090593Z 	/home/runner/work/vitess/vitess/go/stats/rates.go:91 +0x1c1
2020-09-10T11:05:52.1090743Z 
2020-09-10T11:05:52.1090879Z goroutine 38 [select]:
2020-09-10T11:05:52.1091178Z vitess.io/vitess/go/timer.(*Timer).run(0xc00036a660, 0xc00036c610)
2020-09-10T11:05:52.1091344Z 	/home/runner/work/vitess/vitess/go/timer/timer.go:98 +0xc4
2020-09-10T11:05:52.1091495Z created by vitess.io/vitess/go/timer.(*Timer).Start
2020-09-10T11:05:52.1091655Z 	/home/runner/work/vitess/vitess/go/timer/timer.go:86 +0xb2
2020-09-10T11:05:52.1091709Z 
2020-09-10T11:05:52.1091840Z goroutine 405 [IO wait, 9 minutes]:
2020-09-10T11:05:52.1092013Z internal/poll.runtime_pollWait(0x7f24978303c0, 0x72, 0xffffffffffffffff)
2020-09-10T11:05:52.1092278Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/netpoll.go:184 +0x55
2020-09-10T11:05:52.1092494Z internal/poll.(*pollDesc).wait(0xc00011aa18, 0x72, 0x4000, 0x4000, 0xffffffffffffffff)
2020-09-10T11:05:52.1092769Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/internal/poll/fd_poll_runtime.go:87 +0x45
2020-09-10T11:05:52.1092999Z internal/poll.(*pollDesc).waitRead(...)
2020-09-10T11:05:52.1093187Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/internal/poll/fd_poll_runtime.go:92
2020-09-10T11:05:52.1093465Z internal/poll.(*FD).Read(0xc00011aa00, 0xc0004fc000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
2020-09-10T11:05:52.1093737Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/internal/poll/fd_unix.go:169 +0x1cf
2020-09-10T11:05:52.1093947Z net.(*netFD).Read(0xc00011aa00, 0xc0004fc000, 0x4000, 0x4000, 0x19d, 0x0, 0x0)
2020-09-10T11:05:52.1094200Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/net/fd_unix.go:202 +0x4f
2020-09-10T11:05:52.1094407Z net.(*conn).Read(0xc00014af30, 0xc0004fc000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
2020-09-10T11:05:52.1094659Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/net/net.go:184 +0x68
2020-09-10T11:05:52.1094879Z bufio.(*Reader).Read(0xc000203b60, 0xc000440d50, 0x4, 0x4, 0xc000025950, 0x40e8b8, 0x10)
2020-09-10T11:05:52.1095056Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/bufio/bufio.go:226 +0x26a
2020-09-10T11:05:52.1095354Z io.ReadAtLeast(0x105b980, 0xc000203b60, 0xc000440d50, 0x4, 0x4, 0x4, 0xc000203b60, 0xc0001b2ca0, 0x20)
2020-09-10T11:05:52.1095685Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/io/io.go:310 +0x87
2020-09-10T11:05:52.1095916Z io.ReadFull(...)
2020-09-10T11:05:52.1096097Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/io/io.go:329
2020-09-10T11:05:52.1096396Z vitess.io/vitess/go/mysql.(*Conn).readHeaderFrom(0xc0004afa40, 0x105b980, 0xc000203b60, 0x20, 0x8, 0x20)
2020-09-10T11:05:52.1096650Z 	/home/runner/work/vitess/vitess/go/mysql/conn.go:313 +0x87
2020-09-10T11:05:52.1096884Z vitess.io/vitess/go/mysql.(*Conn).readOnePacket(0xc0004afa40, 0xc000468be0, 0x20, 0x20, 0xed4060, 0x18)
2020-09-10T11:05:52.1097059Z 	/home/runner/work/vitess/vitess/go/mysql/conn.go:452 +0x6b
2020-09-10T11:05:52.1097347Z vitess.io/vitess/go/mysql.(*Conn).readPacket(0xc0004afa40, 0xc0001b2ca0, 0x20, 0xc000025b60, 0x40bef8, 0xed4060)
2020-09-10T11:05:52.1097597Z 	/home/runner/work/vitess/vitess/go/mysql/conn.go:474 +0x32
2020-09-10T11:05:52.1097893Z vitess.io/vitess/go/mysql.(*Conn).ReadPacket(0xc0004afa40, 0xc000025c78, 0x108d3e0, 0xc000468be0, 0x0, 0x0)
2020-09-10T11:05:52.1098149Z 	/home/runner/work/vitess/vitess/go/mysql/conn.go:510 +0x2f
2020-09-10T11:05:52.1098386Z vitess.io/vitess/go/mysql.(*filePosFlavor).readBinlogEvent(0xc000203bc0, 0xc0004afa40, 0x2, 0x0, 0x0, 0x0)
2020-09-10T11:05:52.1098650Z 	/home/runner/work/vitess/vitess/go/mysql/flavor_filepos.go:101 +0xb1
2020-09-10T11:05:52.1098893Z vitess.io/vitess/go/mysql.(*Conn).ReadBinlogEvent(...)
2020-09-10T11:05:52.1099078Z 	/home/runner/work/vitess/vitess/go/mysql/flavor.go:223
2020-09-10T11:05:52.1099385Z vitess.io/vitess/go/vt/binlog.(*BinlogConnection).streamEvents.func1(0xc000472ba0, 0xc000367530, 0x10785e0, 0xc00054dbc0)
2020-09-10T11:05:52.1099758Z 	/home/runner/work/vitess/vitess/go/vt/binlog/binlog_connection.go:139 +0xa2
2020-09-10T11:05:52.1100025Z created by vitess.io/vitess/go/vt/binlog.(*BinlogConnection).streamEvents
2020-09-10T11:05:52.1100295Z 	/home/runner/work/vitess/vitess/go/vt/binlog/binlog_connection.go:133 +0xa1
2020-09-10T11:05:52.1100492Z 
2020-09-10T11:05:52.1100629Z goroutine 41 [select, 2 minutes]:
2020-09-10T11:05:52.1100801Z vitess.io/vitess/go/timer.(*Timer).run(0xc00036aae0, 0xc00036c9f0)
2020-09-10T11:05:52.1101055Z 	/home/runner/work/vitess/vitess/go/timer/timer.go:98 +0xc4
2020-09-10T11:05:52.1101230Z created by vitess.io/vitess/go/timer.(*Timer).Start
2020-09-10T11:05:52.1101477Z 	/home/runner/work/vitess/vitess/go/timer/timer.go:86 +0xb2
2020-09-10T11:05:52.1101626Z 
2020-09-10T11:05:52.1101774Z goroutine 42 [select, 2 minutes]:
2020-09-10T11:05:52.1101926Z vitess.io/vitess/go/timer.(*Timer).run(0xc00036ab00, 0xc00036ca30)
2020-09-10T11:05:52.1102177Z 	/home/runner/work/vitess/vitess/go/timer/timer.go:98 +0xc4
2020-09-10T11:05:52.1102352Z created by vitess.io/vitess/go/timer.(*Timer).Start
2020-09-10T11:05:52.1102589Z 	/home/runner/work/vitess/vitess/go/timer/timer.go:86 +0xb2
2020-09-10T11:05:52.1102678Z 
2020-09-10T11:05:52.1102819Z goroutine 44 [select, 9 minutes]:
2020-09-10T11:05:52.1103067Z vitess.io/vitess/go/timer.(*Timer).run(0xc00036aa60, 0xc00036ac60)
2020-09-10T11:05:52.1103355Z 	/home/runner/work/vitess/vitess/go/timer/timer.go:98 +0xc4
2020-09-10T11:05:52.1103629Z created by vitess.io/vitess/go/timer.(*Timer).Start
2020-09-10T11:05:52.1103800Z 	/home/runner/work/vitess/vitess/go/timer/timer.go:86 +0xb2
2020-09-10T11:05:52.1103868Z 
2020-09-10T11:05:52.1104001Z goroutine 368 [semacquire, 9 minutes]:
2020-09-10T11:05:52.1104220Z sync.runtime_Semacquire(0xc00046af38)
2020-09-10T11:05:52.1104402Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/sema.go:56 +0x42
2020-09-10T11:05:52.1104618Z sync.(*WaitGroup).Wait(0xc00046af30)
2020-09-10T11:05:52.1104799Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/sync/waitgroup.go:130 +0x64
2020-09-10T11:05:52.1104920Z runtime.Goexit()
2020-09-10T11:05:52.1105170Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:563 +0xec
2020-09-10T11:05:52.1105333Z testing.(*common).FailNow(0xc0000bb400)
2020-09-10T11:05:52.1105581Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:653 +0x39
2020-09-10T11:05:52.1105926Z testing.(*common).Fatalf(0xc0000bb400, 0xf0d078, 0x1b, 0xc00043da28, 0x4, 0x4)
2020-09-10T11:05:52.1106217Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:716 +0x90
2020-09-10T11:05:52.1106585Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.expectLog(0x10785e0, 0xc00054d880, 0xc0000bb400, 0xd38460, 0xc00040d820, 0xc0004727e0, 0xc00040d840, 0x1, 0x1)
2020-09-10T11:05:52.1106897Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1660 +0x83c
2020-09-10T11:05:52.1107235Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.runCases(0xc0000bb400, 0x0, 0xc000031e70, 0x6, 0x6, 0xef787c, 0x7, 0x0, 0x0, 0x0)
2020-09-10T11:05:52.1107544Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1591 +0x3aa
2020-09-10T11:05:52.1107827Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.TestStatements(0xc0000bb400)
2020-09-10T11:05:52.1108118Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:546 +0x7dd
2020-09-10T11:05:52.1108295Z testing.tRunner(0xc0000bb400, 0xf56c30)
2020-09-10T11:05:52.1108547Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:909 +0xc9
2020-09-10T11:05:52.1108760Z created by testing.(*T).Run
2020-09-10T11:05:52.1108948Z 	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:960 +0x350
2020-09-10T11:05:52.1109008Z 
2020-09-10T11:05:52.1109225Z goroutine 48 [chan receive, 9 minutes]:
2020-09-10T11:05:52.1109507Z vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema.func1(0xef4e74, 0x5, 0xc0003323c0, 0x1078620, 0xc00003c0d8, 0xc00036cfb0, 0xc0002c9500)
2020-09-10T11:05:52.1109881Z 	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:562 +0x2b9
2020-09-10T11:05:52.1110092Z created by vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema
2020-09-10T11:05:52.1110362Z 	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:540 +0xb1
2020-09-10T11:05:52.1110505Z 
2020-09-10T11:05:52.1110663Z goroutine 49 [chan receive, 9 minutes]:
2020-09-10T11:05:52.1110953Z vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema.func1(0xc000331740, 0xc000331620, 0xc0003928a0)
2020-09-10T11:05:52.1111405Z 	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:72 +0xbb
2020-09-10T11:05:52.1111869Z created by vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema
2020-09-10T11:05:52.1112142Z 	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:69 +0x356
2020-09-10T11:05:52.1112337Z 
2020-09-10T11:05:52.1112500Z goroutine 400 [select, 9 minutes]:
2020-09-10T11:05:52.1112830Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.vstream.func1(0xc000010438, 0x1, 0x1, 0xc000439938, 0xc000010438)
2020-09-10T11:05:52.1113160Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1699 +0x1a5
2020-09-10T11:05:52.1113494Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.newUVStreamer.func1(0xc000010438, 0x1, 0x1, 0x0, 0x1)
2020-09-10T11:05:52.1113786Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go:99 +0x6b
2020-09-10T11:05:52.1114138Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*vstreamer).parseEvents.func1(0xc0004bc120, 0xc0004bc120, 0x1893900)
2020-09-10T11:05:52.1114455Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:219 +0x3b7
2020-09-10T11:05:52.1114823Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*vstreamer).parseEvents(0xc0000e29a0, 0x10785e0, 0xc00054db40, 0xc000472ba0, 0x0, 0x0)
2020-09-10T11:05:52.1115450Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:303 +0x63d
2020-09-10T11:05:52.1115779Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*vstreamer).replicate(0xc0000e29a0, 0x1078620, 0xc00003c0d0, 0x0, 0x0)
2020-09-10T11:05:52.1117571Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:177 +0x19b
2020-09-10T11:05:52.1181708Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*vstreamer).Stream(0xc0000e29a0, 0x0, 0x0)
2020-09-10T11:05:52.1182368Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer.go:156 +0x188
2020-09-10T11:05:52.1182751Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*uvstreamer).Stream(0xc0000c0c60, 0x10785e0, 0xc00054d880)
2020-09-10T11:05:52.1183057Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/uvstreamer.go:372 +0x216
2020-09-10T11:05:52.1183446Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.(*Engine).Stream(0xc0004af590, 0x10785e0, 0xc00054d880, 0xef787c, 0x7, 0x0, 0x0, 0x0, 0xc00054d8c0, 0xc0003670e0, ...)
2020-09-10T11:05:52.1183761Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/engine.go:210 +0x166
2020-09-10T11:05:52.1184134Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.vstream(0x10785e0, 0xc00054d880, 0xc0000bb400, 0xef787c, 0x7, 0x0, 0x0, 0x0, 0xc00054d8c0, 0xc0004727e0, ...)
2020-09-10T11:05:52.1184440Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1697 +0x10d
2020-09-10T11:05:52.1184816Z vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.startStream.func1(0xc0004727e0, 0xc00046af30, 0x10785e0, 0xc00054d880, 0xc0000bb400, 0xef787c, 0x7, 0x0, 0x0, 0x0, ...)
2020-09-10T11:05:52.1185122Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1683 +0x163
2020-09-10T11:05:52.1185580Z created by vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.startStream
2020-09-10T11:05:52.1186267Z 	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1679 +0x156
2020-09-10T11:05:52.1186571Z 
2020-09-10T11:05:52.1186767Z goroutine 264 [chan receive, 9 minutes]:
2020-09-10T11:05:52.1187004Z vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema.func1(0xc00045acc0, 0xc00045ac60, 0xc0003cecf0)
2020-09-10T11:05:52.1187212Z 	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:72 +0xbb
2020-09-10T11:05:52.1187394Z created by vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema
2020-09-10T11:05:52.1187690Z 	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:69 +0x356
2020-09-10T11:05:52.1187779Z 
2020-09-10T11:05:52.1188029Z goroutine 109 [chan receive, 9 minutes]:
2020-09-10T11:05:52.1188293Z vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema.func1(0xc000144a20, 0xc0001449c0, 0xc000033e90)
2020-09-10T11:05:52.1188579Z 	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:72 +0xbb
2020-09-10T11:05:52.1188792Z created by vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema
2020-09-10T11:05:52.1189078Z 	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:69 +0x356
2020-09-10T11:05:52.1189595Z 
2020-09-10T11:05:52.1189754Z goroutine 108 [chan receive, 9 minutes]:
2020-09-10T11:05:52.1190096Z vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema.func1(0xef4e74, 0x5, 0xc0003323c0, 0x1078620, 0xc00003c0d8, 0xc0000437a0, 0xc00003d500)
2020-09-10T11:05:52.1190371Z 	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:562 +0x2b9
2020-09-10T11:05:52.1190582Z created by vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema
2020-09-10T11:05:52.1190848Z 	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:540 +0xb1
2020-09-10T11:05:52.1191031Z 
2020-09-10T11:05:52.1191194Z goroutine 402 [chan receive, 9 minutes]:
2020-09-10T11:05:52.1191480Z vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema.func1(0xc000203800, 0xc0002037a0, 0xc000367110)
2020-09-10T11:05:52.1191735Z 	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:72 +0xbb
2020-09-10T11:05:52.1191928Z created by vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema
2020-09-10T11:05:52.1192104Z 	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:69 +0x356
2020-09-10T11:05:52.1192161Z 
2020-09-10T11:05:52.1192381Z goroutine 401 [chan receive, 9 minutes]:
2020-09-10T11:05:52.1192661Z vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema.func1(0xef4e74, 0x5, 0xc0003323c0, 0x1078620, 0xc00003c0d8, 0xc00018b9f0, 0xc00046af50)
2020-09-10T11:05:52.1192931Z 	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:562 +0x2b9
2020-09-10T11:05:52.1193210Z created by vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema
2020-09-10T11:05:52.1193501Z 	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:540 +0xb1
2020-09-10T11:05:52.1193699Z FAIL	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer	602.596s
```

**Comment by rohit-nayak-ps** [comment]
haven't seen this for a while
