### ISSUE TITLE
Flaky TestStaticConfigHUPWithRotation 

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#6866]
--- FAIL: TestStaticConfigHUPWithRotation (0.44s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 44 [running]:
testing.tRunner.func1(0xc0000c2d00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:874 +0x3a3
panic(0x9db940, 0xc000306960)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
vitess.io/vitess/go/mysql.hupTestWithRotation(0xc0000c2d00, 0xc0003a02a0, 0xc00009a3b0, 0xa20106, 0x4, 0xa20112, 0x4)
	/home/runner/work/vitess/vitess/go/mysql/auth_server_static_test.go:210 +0x5aa
vitess.io/vitess/go/mysql.TestStaticConfigHUPWithRotation(0xc0000c2d00)
	/home/runner/work/vitess/vitess/go/mysql/auth_server_static_test.go:179 +0x4e5

**Comment by deepthi** [comment]
duplicate of #6485
