### ISSUE TITLE
[Flaky Test] TestParallelRunnerApprovalFirstRunningSecondRunning Failing

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#6948]
```
--- FAIL: TestParallelRunnerApprovalFirstRunningSecondRunning (0.00s)
panic: close of closed channel [recovered]
	panic: close of closed channel

goroutine 76 [running]:
testing.tRunner.func1(0xc0002a4200)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:874 +0x69f
panic(0xe8a900, 0x10c6890)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
vitess.io/vitess/go/vt/workflow.TestParallelRunnerApprovalFirstRunningSecondRunning(0xc0002a4200)
	/home/runner/work/vitess/vitess/go/vt/workflow/parallel_runner_test.go:363 +0xa09
testing.tRunner(0xc0002a4200, 0xfb00b0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:960 +0x652
FAIL	vitess.io/vitess/go/vt/workflow	0.065s
```

**Comment by rohit-nayak-ps** [comment]
this has been fixed
