### ISSUE TITLE
[Flaky Test] Vstreamer test failing

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#6971]
```
E1029 14:34:33.287146   24300 planbuilder.go:311] syntax error at position 4 near 'bad'
E1029 14:34:33.292731   24300 planbuilder.go:311] unsupported: delete from t1
E1029 14:34:33.293037   24300 planbuilder.go:311] unsupported: select * from t1, t2
E1029 14:34:33.293287   24300 planbuilder.go:311] unsupported: select * from t1 join t2
E1029 14:34:33.293548   24300 planbuilder.go:311] unsupported: select * from a.t1
E1029 14:34:33.295615   24300 planbuilder.go:315] unsupported: select expression table t2 does not match the table entry name t1
E1029 14:34:33.296088   24300 planbuilder.go:327] unsupported: *, id
E1029 14:34:33.296411   24300 planbuilder.go:323] unsupported constraint: max(id)
E1029 14:34:33.296682   24300 planbuilder.go:323] unsupported: id
E1029 14:34:33.297006   24300 planbuilder.go:323] unexpected: *
E1029 14:34:33.297309   24300 planbuilder.go:323] unexpected: 1
E1029 14:34:33.297628   24300 planbuilder.go:323] vindex must be Unique to be used for VReplication: lookup
E1029 14:34:33.299168   24300 planbuilder.go:323] malformed spec: doesn't define a range: "80"
E1029 14:34:33.299605   24300 planbuilder.go:323] unexpected in_keyrange parameter: '-80-'
E1029 14:34:33.299830   24300 planbuilder.go:327] unsupported: *
E1029 14:34:33.299985   24300 planbuilder.go:327] column none not found in table t1
E1029 14:34:33.300221   24300 planbuilder.go:327] unsupported function: max(val)
E1029 14:34:33.300447   24300 planbuilder.go:327] unsupported: id + 1
E1029 14:34:33.300654   24300 planbuilder.go:327] unsupported qualifier for column: t1.id
E1029 14:34:33.300882   24300 planbuilder.go:323] unsupported: *
E1029 14:34:33.301124   24300 planbuilder.go:323] unsupported: 1 + 1
E1029 14:34:33.422441   24300 planbuilder.go:327] only the integer literal 1 is supported
E1029 14:34:33.422492   24300 rowstreamer.go:131] only the integer literal 1 is supported
E1029 14:34:33.423163   24300 planbuilder.go:327] only integer literals are supported
E1029 14:34:33.423206   24300 rowstreamer.go:131] only integer literals are supported
E1029 14:34:42.270486   24300 vstreamer_test.go:1818] [begin insert into t1 values (4, 1, 'aaa') insert into t1 values (1, 4, 'aaa') commit] (1): event:
"type:ROW row_event:<table_name:\"t1\" row_changes:<after:<lengths:1 lengths:1 lengths:3 values:\"14aaa\" > > > ", want
testing.(*common).Fatalf(0xc0000dc300, 0x14251d0, 0x1b, 0xc000299bd0, 0x4, 0x4)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:716 +0x9e
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.expectLog(0x162d5c0, 0xc0001b10c0, 0xc0000dc300, 0x124c4a0, 0xc000376c80, 0xc000364060, 0xc000265f10, 0x1, 0x1)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:1819 +0xa5f
vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer.TestREKeyRange(0xc0000dc300)
	/home/runner/work/vitess/vitess/go/vt/vttablet/tabletserver/vstreamer/vstreamer_test.go:896 +0x9e5
testing.tRunner(0xc0000dc300, 0x14701c8)
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:909 +0x19a
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.13.15/x64/src/testing/testing.go:960 +0x652

goroutine 455 [chan receive, 9 minutes]:
vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema.func1(0x140c65b, 0x5, 0xc0002fa640, 0x162d600, 0xc0000ba018, 0xc000045ad0, 0xc0005385f0)
	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:562 +0xb2
created by vitess.io/vitess/go/vt/srvtopo.(*ResilientServer).WatchSrvVSchema
	/home/runner/work/vitess/vitess/go/vt/srvtopo/resilient_server.go:540 +0xe9

goroutine 511 [chan receive, 9 minutes]:
vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema.func1(0xc000209500, 0xc0002094a0, 0xc0001bf560)
	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:72 +0xcc
created by vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema
	/home/runner/work/vitess/vitess/go/vt/topo/srv_vschema.go:69 +0x4f6
FAIL	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer	602.712s
```

**Comment by deepthi** [comment]
Saw a different failure today:
```
E0312 21:29:27.036193   32418 vstreamer_test.go:2024] [begin insert into stream1 values (1, 'aaa') update stream1 set val='bbb' where id = 1 commit] (1): event:
"type:FIELD field_event:<table_name:\"stream1\" fields:<name:\"id\" type:INT32 table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"id\" column_length:11 charset:63 > fields:<name:\"val\" type:VARBINARY table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"val\" column_length:256 charset:63 > > ", want
"type:FIELD field_event:<table_name:\"stream1\" fields:<name:\"id\" type:INT32 table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"id\" column_length:11 charset:63 > fields:<name:\"val\" type:VARBINARY table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"val\" column_length:128 charset:63 > > "
--- FAIL: TestStatements (2.98s)
Error:     vstreamer_test.go:2064: Received events: [type:GTID gtid:"MySQL56/fe54624a-8379-11eb-a332-000d3a02d3fc:1-113"  type:OTHER ]
Error:     vstreamer_test.go:2064: Received events: [type:BEGIN timestamp:1615584566 current_time:1615584566987792819  type:FIELD timestamp:1615584566 field_event:<table_name:"stream1" fields:<name:"id" type:INT32 table:"stream1" org_table:"stream1" database:"vttest" org_name:"id" column_length:11 charset:63 flags:53251 > fields:<name:"val" type:VARBINARY table:"stream1" org_table:"stream1" database:"vttest" org_name:"val" column_length:128 charset:63 flags:128 > > current_time:1615584566989152822  type:ROW timestamp:1615584566 row_event:<table_name:"stream1" row_changes:<after:<lengths:1 lengths:3 values:"1aaa" > > > current_time:1615584566989163922  type:ROW timestamp:1615584566 row_event:<table_name:"stream1" row_changes:<before:<lengths:1 lengths:3 values:"1aaa" > after:<lengths:1 lengths:3 values:"1bbb" > > > current_time:1615584566989178422  type:GTID timestamp:1615584566 gtid:"MySQL56/fe54624a-8379-11eb-a332-000d3a02d3fc:1-114" current_time:1615584566989210922  type:COMMIT timestamp:1615584566 current_time:1615584566989211022 ]
Error:     vstreamer_test.go:2064: Received events: [type:GTID timestamp:1615584566 gtid:"MySQL56/fe54624a-8379-11eb-a332-000d3a02d3fc:1-115" current_time:1615584566995549337  type:DDL timestamp:1615584566 statement:"alter table stream1 change column val val varbinary(128)" current_time:1615584566995549437 ]
Error:     vstreamer_test.go:2064: Received events: [type:GTID timestamp:1615584566 gtid:"MySQL56/fe54624a-8379-11eb-a332-000d3a02d3fc:1-116" current_time:1615584567006572562  type:DDL timestamp:1615584566 statement:"/* prefix */ alter table stream1 change column val val varbinary(256) /* suffix */" current_time:1615584567006572662 ]
Error:     vstreamer_test.go:2064: Received events: [type:BEGIN timestamp:1615584567 current_time:1615584567007677164  type:FIELD timestamp:1615584567 field_event:<table_name:"stream1" fields:<name:"id" type:INT32 table:"stream1" org_table:"stream1" database:"vttest" org_name:"id" column_length:11 charset:63 flags:53251 > fields:<name:"val" type:VARBINARY table:"stream1" org_table:"stream1" database:"vttest" org_name:"val" column_length:256 charset:63 flags:128 > > current_time:1615584567008923967  type:ROW timestamp:1615584567 row_event:<table_name:"stream1" row_changes:<after:<lengths:1 lengths:3 values:"2bbb" > > > current_time:1615584567008933067  type:FIELD timestamp:1615584567 field_event:<table_name:"stream2" fields:<name:"id" type:INT32 table:"stream2" org_table:"stream2" database:"vttest" org_name:"id" column_length:11 charset:63 flags:53251 > fields:<name:"val" type:VARBINARY table:"stream2" org_table:"stream2" database:"vttest" org_name:"val" column_length:128 charset:63 flags:128 > > current_time:1615584567010192270  type:ROW timestamp:1615584567 row_event:<table_name:"stream2" row_changes:<after:<lengths:1 lengths:3 values:"1aaa" > > > current_time:1615584567010202270  type:ROW timestamp:1615584567 row_event:<table_name:"stream1" row_changes:<before:<lengths:1 lengths:3 values:"1bbb" > after:<lengths:1 lengths:3 values:"1ccc" > > row_changes:<before:<lengths:1 lengths:3 values:"2bbb" > after:<lengths:1 lengths:3 values:"2ccc" > > > current_time:1615584567010217070  type:ROW timestamp:1615584567 row_event:<table_name:"stream1" row_changes:<before:<lengths:1 lengths:3 values:"1ccc" > > row_changes:<before:<lengths:1 lengths:3 values:"2ccc" > > > current_time:1615584567010222670  type:GTID timestamp:1615584567 gtid:"MySQL56/fe54624a-8379-11eb-a332-000d3a02d3fc:1-117" current_time:1615584567010231770  type:COMMIT timestamp:1615584567 current_time:1615584567010231870 ]
Error:     vstreamer_test.go:2064: Received events: [type:GTID timestamp:1615584567 gtid:"MySQL56/fe54624a-8379-11eb-a332-000d3a02d3fc:1-118" current_time:1615584567016777785  type:DDL timestamp:1615584567 statement:"truncate table stream2" current_time:1615584567016777985 ]
Error:     vstreamer_test.go:2064: Received events: [type:GTID timestamp:1615584567 gtid:"MySQL56/fe54624a-8379-11eb-a332-000d3a02d3fc:1-119" current_time:1615584567028629312  type:DDL timestamp:1615584567 statement:"/* prefix */ alter table stream1 change column val val varbinary(128) /* suffix */" current_time:1615584567028629412 ]
Error:     vstreamer_test.go:2064: Received events: [type:GTID gtid:"FilePos/vt-0000000001-bin.000001:33828"  type:OTHER ]
Error:     vstreamer_test.go:2064: Received events: [type:BEGIN timestamp:1615584567 current_time:1615584567034403625  type:FIELD timestamp:1615584567 field_event:<table_name:"stream1" fields:<name:"id" type:INT32 table:"stream1" org_table:"stream1" database:"vttest" org_name:"id" column_length:11 charset:63 > fields:<name:"val" type:VARBINARY table:"stream1" org_table:"stream1" database:"vttest" org_name:"val" column_length:256 charset:63 > > current_time:1615584567036011828  type:ROW timestamp:1615584567 row_event:<table_name:"stream1" row_changes:<after:<lengths:1 lengths:3 values:"1aaa" > > > current_time:1615584567036034728  type:ROW timestamp:1615584567 row_event:<table_name:"stream1" row_changes:<before:<lengths:1 lengths:3 values:"1aaa" > after:<lengths:1 lengths:3 values:"1bbb" > > > current_time:1615584567036048828  type:GTID timestamp:1615584567 gtid:"FilePos/vt-0000000001-bin.000001:34235" current_time:1615584567036054028  type:COMMIT timestamp:1615584567 current_time:1615584567036054128 ]
Error:     vstreamer_test.go:2025: [begin insert into stream1 values (1, 'aaa') update stream1 set val='bbb' where id = 1 commit] (1): event:
        "type:FIELD field_event:<table_name:\"stream1\" fields:<name:\"id\" type:INT32 table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"id\" column_length:11 charset:63 > fields:<name:\"val\" type:VARBINARY table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"val\" column_length:256 charset:63 > > ", want
        "type:FIELD field_event:<table_name:\"stream1\" fields:<name:\"id\" type:INT32 table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"id\" column_length:11 charset:63 > fields:<name:\"val\" type:VARBINARY table:\"stream1\" org_table:\"stream1\" database:\"vttest\" org_name:\"val\" column_length:128 charset:63 > > "
Error:     vstreamer_test.go:2064: Received events: [type:HEARTBEAT timestamp:1615584567 current_time:1615584567936269362 ]
Error:     vstreamer_test.go:2070: VStream timed out waiting for events
E0312 21:29:30.303070   32418 vstreamer.go:889] stream (at source tablet) error @ fe54624a-8379-11eb-a332-000d3a02d3fc:1-164: cannot determine table columns for ddl_test2: event has [3 15 15], schema as [name:"id" type:INT32 table:"ddl_test2" org_table:"ddl_test2" database:"vttest" org_name:"id" column_length:11 charset:63 flags:53251  name:"val1" type:VARBINARY table:"ddl_test2" org_table:"ddl_test2" database:"vttest" org_name:"val1" column_length:128 charset:63 flags:128 ]
E0312 21:29:30.484933   32418 vstreamer_test.go:1631] TestJSON: flavor is MySQL56
E0312 21:29:30.525776   32418 vstreamer.go:889] stream (at source tablet) error @ fe54624a-8379-11eb-a332-000d3a02d3fc:1-225: partial row image encountered: ensure binlog_row_image is set to 'full'
FAIL
FAIL	vitess.io/vitess/go/vt/vttablet/tabletserver/vstreamer	19.904s
```

**Comment by rohit-nayak-ps** [comment]
these have been fixed
