### ISSUE TITLE
panic from LFU cache when cache_size is set to 0

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#7549]
#### Overview of the Issue
```
panic: NumCounters can't be zero
goroutine 1 [running]:
vitess.io/vitess/go/cache.NewRistrettoCache(0x0, 0x2000000, 0x24f9fc0, 0xc000cdfb58)	/vt/src/vitess.io/vitess/go/cache/ristretto.go:25 +0x125
vitess.io/vitess/go/cache.NewDefaultCacheImpl(0xc000cdfbe0, 0xc0000fac00, 0xc000f17e90)	/vt/src/vitess.io/vitess/go/cache/cache.go:54 +0x16b
vitess.io/vitess/go/vt/vttablet/tabletserver.NewQueryEngine(0x276f060, 0xc0000b7500, 0xc000fee000, 0xc000fde230)	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/query_engine.go:173 +0xb1
vitess.io/vitess/go/vt/vttablet/tabletserver.NewTabletServer(0x0, 0x0, 0xc0000fac00, 0xc000efdd00, 0x7ffd30894b8d, 0x5, 0x29f4e420, 0x0, 0x0, 0x0, ...)	/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:177 +0x647
main.createTabletServer(0xc0000fac00, 0xc000efdd00, 0xc000efd200, 0x0)	/vt/src/vitess.io/vitess/go/cmd/vttablet/vttablet.go:206 +0xdd
main.main()	/vt/src/vitess.io/vitess/go/cmd/vttablet/vttablet.go:80 +0x125
```
#### Reproduction Steps
Run local example with `queryserver-config-query-cache-size=0` on vttablet and `-gate_query_cache_size=0` on vtgate.

#### Binary version
latest

#### Suggested fix
Don't create the cache at all if cache_size is given as 0.

**Comment by deepthi** [comment]
Slack thread with original report: https://vitess.slack.com/archives/C0PQY0PTK/p1613667516376500
