### ISSUE TITLE
vttestserver cannot work with a persistent -data_dir= volume

### ISSUE THREAD

**Issue by hkdsun** [vitessio/vitess#7717]
#### Overview of the Issue

In order to run `vttestserver` as a substitute to a `mysql` container in development environments, we should theoretically be able to run the vttestserver container, put some data in there, stop the container, and re-run the container with the previous data still intact, if the `-data_dir=` argument is provided and is mounted to a persistent volume on the host.

This is essential and expected in our development environments.

#### Reproduction Steps 

* start a container with `-data_dir` pointed to a docker volume: 
    * `docker run -it --volume=/tmp/vt:/tmp/vt/ vitess/vttestserver vttestserver -port 2222 -data_dir /tmp/vt -alsologtostderr -num_shards=1,1,1 -keyspaces=dev,archive,shard1`
* stop the container
* run it again with the same arguments as before
  * `docker run -it --volume=/tmp/vt:/tmp/vt/ vitess/vttestserver vttestserver -port 2222 -data_dir /tmp/vt -alsologtostderr -num_shards=1,1,1 -keyspaces=dev,archive,shard1`

The error produced is as follows:

```
vitess_test_1  | F0317 13:06:00.523293       1 main.go:238] mkdir /vt/vtdataroot/test_volume/logs: file exists
vitess_test_1  | goroutine 1 [running]:
vitess_test_1  | github.com/golang/glog.stacks(0xc000094a00, 0xc0000c2000, 0x5e, 0xb2)
vitess_test_1  |        /go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:769 +0xb9
vitess_test_1  | github.com/golang/glog.(*loggingT).output(0x1270680, 0xc000000003, 0xc000033960, 0x11b1a05, 0x7, 0xee, 0x0)
vitess_test_1  |        /go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:720 +0x3b3
vitess_test_1  | github.com/golang/glog.(*loggingT).printDepth(0x1270680, 0x3, 0x1, 0xc00006c720, 0x1, 0x1)
vitess_test_1  |        /go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:646 +0x12d
vitess_test_1  | github.com/golang/glog.(*loggingT).print(...)
vitess_test_1  |        /go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:637
vitess_test_1  | github.com/golang/glog.Fatal(0xc00006c720, 0x1, 0x1)
vitess_test_1  |        /go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:1128 +0x5c
vitess_test_1  | main.runCluster(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
vitess_test_1  |        /vt/src/vitess.io/vitess/go/cmd/vttestserver/main.go:238 +0x342
vitess_test_1  | main.main()
vitess_test_1  |        /vt/src/vitess.io/vitess/go/cmd/vttestserver/main.go:221 +0x4a
test_case_vitess_test_1 exited with code 255
```

#### Operating system and Environment details

Universally applicable. Reproduced on MacOS, and Ubuntu.

**Comment by hkdsun** [comment]
I have a proposed fix in https://github.com/vitessio/vitess/pull/7718

cc @jeremycole @alexrs @psyxoz
