### ISSUE TITLE
Flaky test TestStreamMigrateMainflow

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#7823]
`TestStreamMigrateMainflow` keeps failing on unrelated changes. Example:

https://github.com/vitessio/vitess/pull/7782/checks?check_run_id=2320800615

**Comment by rohit-nayak-ps** [comment]
I think this is not related to that test specifically because of these errors with other tests before that test failure:
```
--- FAIL: TestTLSServer (130.91s)
    server_test.go:865: 
        	Error Trace:	server_test.go:865
        	Error:      	Received unexpected error:
        	            	net.Dial(fv-az151-672:37161) failed: dial tcp 10.1.0.25:37161: connect: connection timed out (errno 2003) (sqlstate HY000)
        	Test:       	TestTLSServer
E0412 09:03:15.607078   17749 auth_server_static.go:142] Error parsing auth server config: EOF


--- FAIL: TestZk2Topo (65.68s)
Error:     testing.go:49: === checkKeyspace
Error:     server_test.go:60: CreateCellInfo() failed: deadline exceeded: /test-0/global/cells/test/CellInfo
FAIL
FAIL	vitess.io/vitess/go/vt/topo/zk2topo	65.705s


ok  	vitess.io/vitess/go/vt/vtctl/workflow/vexec	0.057s
E0412 09:05:40.568664   27701 api.go:131] HTTP error on /api/tablet_statuses/cell1/REPLICA/lag: can't get tablet_statuses: invalid target path: "cell1/REPLICA/lag"  expected path: ?keyspace=<keyspace>&cell=<cell>&type=<type>&metric=<metric>, request: &http.Request{Method:"GET", URL:(*url.URL)(0xc0003514d0), Proto:"HTTP/1.1", ProtoMajor:1, ProtoMinor:1, Header:http.Header{"Accept-Encoding":[]string{"gzip"}, "User-Agent":[]string{"Go-http-client/1.1"}}, Body:http.noBody{}, GetBody:(func() (io.ReadCloser, error))(nil), ContentLength:0, TransferEncoding:[]string(nil), Close:false, Host:"127.0.0.1:41351", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"127.0.0.1:41230", RequestURI:"/api/tablet_statuses/cell1/REPLICA/lag", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.cancelCtx)(0xc000332d80)}


W0412 09:05:40.669577   27701 tm_init.go:441] rebuildKeyspace failed, will retry every 1s: keyspace partition for MASTER in cell cell1 does not end with max key
--- FAIL: TestRealtimeStatsWithQueryService (506.41s)
panic: StartActionLoop failed. [recovered]
	panic: StartActionLoop failed.

goroutine 154 [running]:


```

I see that `StartActionLoop failed` error in other runs. Creating a separate issue for this.
