### ISSUE TITLE
Uncaught panic in vtgate schema tracker

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#8803]
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

Some of the unit tests are failing on a panic in the production code, so I'm erring on the side of this being potentially a Real Issue that can happen in production.

[Test output](https://github.com/vitessio/vitess/pull/8801/checks?check_run_id=3587684158#step:4:144):

```
ERROR: logging before flag.Parse: E0913 13:49:38.770155     940 syslogger.go:149] can't connect to syslog
panic: runtime error: index out of range [2] with length 2

goroutine 44 [running]:
vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).updateTables(0xc000264d70, {0xddf21a, 0x2}, 0x2)
	/vt/src/vitess.io/vitess/go/vt/vtgate/schema/tracker.go:189 +0x427
vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).updateSchema(0xc000264d70, 0xc0003c0000)
	/vt/src/vitess.io/vitess/go/vt/vtgate/schema/tracker.go:181 +0x3b5
vitess.io/vitess/go/vt/vtgate/schema.(*updateController).consume(0xc0002d5300)
	/vt/src/vitess.io/vitess/go/vt/vtgate/schema/uptate_controller.go:61 +0xae
created by vitess.io/vitess/go/vt/vtgate/schema.(*updateController).add
	/vt/src/vitess.io/vitess/go/vt/vtgate/schema/uptate_controller.go:119 +0x153
FAIL	vitess.io/vitess/go/vt/vtgate/schema	0.044s
```

**Comment by harshit-gangal** [comment]
is this happening on main branch or a release?

**Comment by harshit-gangal** [comment]
I verified the code, it is not an actual issue but related to test setup.

The query that will be sent down to MySQL will contain 3 columns. In our sandbox setup, if the resultset is not provided then it returns a result with 2 columns, hence panic on accessing 3rd columns.

I am trying to find the test case where it can happen, not able to fail locally.

**Comment by frouioui** [comment]
@harshit-gangal @ajm188 can we close this issue?
