### ISSUE TITLE
Flaky Schema Tracking Test

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#9092]
```
ERROR: logging before flag.Parse: E1026 18:34:00.982535    2394 syslogger.go:149] can't connect to syslog
==================
WARNING: DATA RACE
Write at 0x00c0004b42a0 by goroutine 46:
  vitess.io/vitess/go/vt/vttablet/sandboxconn.(*SandboxConn).Execute()
      /vt/src/vitess.io/vitess/go/vt/vttablet/sandboxconn/sandboxconn.go:168 +0x79e
  vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).updateSchema()
      /vt/src/vitess.io/vitess/go/vt/vtgate/schema/tracker.go:174 +0x2f4
  vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).updateSchema-fm()
      /vt/src/vitess.io/vitess/go/vt/vtgate/schema/tracker.go:166 +0x44
  vitess.io/vitess/go/vt/vtgate/schema.(*updateController).consume()
      /vt/src/vitess.io/vitess/go/vt/vtgate/schema/uptate_controller.go:67 +0xe5
  vitess.io/vitess/go/vt/vtgate/schema.(*updateController).add·dwrap·9()
      /vt/src/vitess.io/vitess/go/vt/vtgate/schema/uptate_controller.go:154 +0x39

Previous read at 0x00c0004b42a0 by goroutine 44:
  vitess.io/vitess/go/vt/vttablet/sandboxconn.(*SandboxConn).StringQueries()
      /vt/src/vitess.io/vitess/go/vt/vttablet/sandboxconn/sandboxconn.go:620 +0x44
  vitess.io/vitess/go/vt/vtgate/schema.TestTracking.func1()
      /vt/src/vitess.io/vitess/go/vt/vtgate/schema/tracker_test.go:186 +0x5a4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47

Goroutine 46 (running) created at:
  vitess.io/vitess/go/vt/vtgate/schema.(*updateController).add()
      /vt/src/vitess.io/vitess/go/vt/vtgate/schema/uptate_controller.go:154 +0x34b
  vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).Start.func1()
      /vt/src/vitess.io/vitess/go/vt/vtgate/schema/tracker.go:103 +0x6e
  vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).Start·dwrap·2()
      /vt/src/vitess.io/vitess/go/vt/vtgate/schema/tracker.go:109 +0x66

Goroutine 44 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  vitess.io/vitess/go/vt/vtgate/schema.TestTracking()
      /vt/src/vitess.io/vitess/go/vt/vtgate/schema/tracker_test.go:141 +0x1db5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
==================
panic: runtime error: index out of range [2] with length 2

goroutine 42 [running]:
vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).updateTables(0xc00032fd10, {0x12ebbb4, 0x2}, 0xc0002017a0)
	/vt/src/vitess.io/vitess/go/vt/vtgate/schema/tracker.go:198 +0x792
vitess.io/vitess/go/vt/vtgate/schema.(*Tracker).updateSchema(0xc00032fd10, 0xc00032fdb0)
	/vt/src/vitess.io/vitess/go/vt/vtgate/schema/tracker.go:190 +0x61d
vitess.io/vitess/go/vt/vtgate/schema.(*updateController).consume(0xc00044bdc0)
	/vt/src/vitess.io/vitess/go/vt/vtgate/schema/uptate_controller.go:67 +0xe6
created by vitess.io/vitess/go/vt/vtgate/schema.(*updateController).add
	/vt/src/vitess.io/vitess/go/vt/vtgate/schema/uptate_controller.go:154 +0x34c
FAIL	vitess.io/vitess/go/vt/vtgate/schema	0.100s
```

**Comment by ajm188** [comment]
@harshit-gangal i would guess we don't see this any longer, can you confirm and close if so?

**Comment by harshit-gangal** [comment]
This is fixed to my knowledge. Let's close this we can open again if anyone sees it.
