### ISSUE TITLE
Flaky upgrade/downgrade test

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#9993]
### Overview of the Issue

Upgrade/Downgrade query serving test is flaky

### Reproduction Steps

Test fails in CI on unrelated PRs

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
CI
```

### Log Fragments

```sh
https://github.com/vitessio/vitess/runs/5703114998?check_suite_focus=true

2022-03-26T12:29:23.3196475Z I0326 12:29:23.318833  114077 vtgate_process.go:110] Running vtgate with command: vtgate --topo_implementation etcd2 --topo_global_server_address localhost:19802 --topo_global_root /vitess/global --log_dir /home/runner/work/vitess/vitess/vtdataroot/vt_29648119/vtroot_19801/tmp_19803 --log_queries_to_file /home/runner/work/vitess/vitess/vtdataroot/vt_29648119/vtroot_19801/tmp_19803/vtgate_querylog.txt --port 19810 --grpc_port 19811 --mysql_server_port 19812 --mysql_server_socket_path /home/runner/work/vitess/vitess/vtdataroot/vt_29648119/vtroot_19801/tmp_19803/mysql.sock --cell zone1 --cells_to_watch zone1 --tablet_types_to_wait PRIMARY,REPLICA --service_map grpc-tabletmanager,grpc-throttler,grpc-queryservice,grpc-updatestream,grpc-vtctl,grpc-vtworker,grpc-vtgateservice --mysql_auth_server_impl none --planner_version Gen4CompareV3 --schema_change_signal --vschema_ddl_authorized_users %
2022-03-26T12:40:17.9521025Z SIGQUIT: quit
2022-03-26T12:40:17.9522235Z PC=0x46d061 m=0 sigcode=0
2022-03-26T12:40:17.9522725Z 
2022-03-26T12:40:17.9523055Z goroutine 0 [idle]:
2022-03-26T12:40:17.9523758Z runtime.futex()
2022-03-26T12:40:17.9524586Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/sys_linux_amd64.s:552 +0x21
2022-03-26T12:40:17.9531715Z runtime.futexsleep(0x10000000000?, 0x0?, 0x7ffd8ccef948?)
2022-03-26T12:40:17.9534894Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/os_linux.go:66 +0x36
2022-03-26T12:40:17.9535661Z runtime.notesleep(0x1f53f88)
2022-03-26T12:40:17.9536386Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/lock_futex.go:159 +0x87
2022-03-26T12:40:17.9536989Z runtime.mPark(...)
2022-03-26T12:40:17.9537688Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:1449
2022-03-26T12:40:17.9538298Z runtime.stopm()
2022-03-26T12:40:17.9538939Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:2228 +0x8d
2022-03-26T12:40:17.9539536Z runtime.findrunnable()
2022-03-26T12:40:17.9540228Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:2804 +0x865
2022-03-26T12:40:17.9540779Z runtime.schedule()
2022-03-26T12:40:17.9541438Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:3187 +0x239
2022-03-26T12:40:17.9542038Z runtime.park_m(0xc0000b2d00?)
2022-03-26T12:40:17.9542695Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/proc.go:3336 +0x14d
2022-03-26T12:40:17.9543251Z runtime.mcall()
2022-03-26T12:40:17.9543978Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/asm_amd64.s:425 +0x43
2022-03-26T12:40:17.9544205Z 
2022-03-26T12:40:17.9544362Z goroutine 1 [chan receive, 10 minutes]:
2022-03-26T12:40:17.9544764Z vitess.io/vitess/go/test/endtoend/cluster.(*VtgateProcess).TearDown(0xc000379588)
2022-03-26T12:40:17.9545702Z 	/home/runner/work/vitess/vitess/go/test/endtoend/cluster/vtgate_process.go:216 +0x191
2022-03-26T12:40:17.9546218Z vitess.io/vitess/go/test/endtoend/cluster.(*LocalProcessCluster).Teardown(0xc000379200)
2022-03-26T12:40:17.9546733Z 	/home/runner/work/vitess/vitess/go/test/endtoend/cluster/cluster_process.go:725 +0xeb
2022-03-26T12:40:17.9547249Z vitess.io/vitess/go/test/endtoend/vtgate/schematracker/unsharded.TestMain.func1(0xc000094180?)
2022-03-26T12:40:17.9547853Z 	/home/runner/work/vitess/vitess/go/test/endtoend/vtgate/schematracker/unsharded/st_unsharded_test.go:77 +0x45c
2022-03-26T12:40:17.9548394Z vitess.io/vitess/go/test/endtoend/vtgate/schematracker/unsharded.TestMain(0x4427b1?)
2022-03-26T12:40:17.9548961Z 	/home/runner/work/vitess/vitess/go/test/endtoend/vtgate/schematracker/unsharded/st_unsharded_test.go:85 +0x8f
2022-03-26T12:40:17.9549345Z main.main()
2022-03-26T12:40:17.9549623Z 	_testmain.go:49 +0x1d3
2022-03-26T12:40:17.9549785Z 
2022-03-26T12:40:17.9549901Z goroutine 6 [chan receive]:
2022-03-26T12:40:17.9550254Z github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
2022-03-26T12:40:17.9551156Z 	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x6a
2022-03-26T12:40:17.9551568Z created by github.com/golang/glog.init.0
2022-03-26T12:40:17.9552177Z 	/home/runner/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x1bf
2022-03-26T12:40:17.9552433Z 
2022-03-26T12:40:17.9552574Z goroutine 35 [syscall, 10 minutes]:
2022-03-26T12:40:17.9552868Z os/signal.signal_recv()
2022-03-26T12:40:17.9553247Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/runtime/sigqueue.go:151 +0x2f
2022-03-26T12:40:17.9553579Z os/signal.loop()
2022-03-26T12:40:17.9553971Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/signal/signal_unix.go:23 +0x19
2022-03-26T12:40:17.9554345Z created by os/signal.Notify.func1.1
2022-03-26T12:40:17.9554748Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/signal/signal.go:151 +0x2a
2022-03-26T12:40:17.9555107Z 
2022-03-26T12:40:17.9555249Z goroutine 59 [select, 10 minutes]:
2022-03-26T12:40:17.9555589Z net/http.(*persistConn).readLoop(0xc00014c120)
2022-03-26T12:40:17.9556012Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:2213 +0xda5
2022-03-26T12:40:17.9556396Z created by net/http.(*Transport).dialConn
2022-03-26T12:40:17.9558871Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:1750 +0x173e
2022-03-26T12:40:17.9559319Z 
2022-03-26T12:40:17.9559467Z goroutine 24 [syscall, 10 minutes]:
2022-03-26T12:40:17.9559826Z syscall.Syscall6(0xf7, 0x1, 0x1bdb7, 0xc00046ee30, 0x1000004, 0x0, 0x0)
2022-03-26T12:40:17.9560274Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/syscall/asm_linux_amd64.s:43 +0x5
2022-03-26T12:40:17.9560677Z os.(*Process).blockUntilWaitable(0xc0000473e0)
2022-03-26T12:40:17.9561090Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/wait_waitid.go:32 +0x9c
2022-03-26T12:40:17.9561435Z os.(*Process).wait(0xc0000473e0)
2022-03-26T12:40:17.9561821Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/exec_unix.go:22 +0x28
2022-03-26T12:40:17.9562149Z os.(*Process).Wait(...)
2022-03-26T12:40:17.9562506Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/exec.go:132
2022-03-26T12:40:17.9563002Z os/exec.(*Cmd).Wait(0xc00021d760)
2022-03-26T12:40:17.9563389Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/exec/exec.go:507 +0x54
2022-03-26T12:40:17.9563815Z vitess.io/vitess/go/test/endtoend/cluster.(*TopoProcess).SetupEtcd.func1()
2022-03-26T12:40:17.9564327Z 	/home/runner/work/vitess/vitess/go/test/endtoend/cluster/topo_process.go:101 +0x29
2022-03-26T12:40:17.9564800Z created by vitess.io/vitess/go/test/endtoend/cluster.(*TopoProcess).SetupEtcd
2022-03-26T12:40:17.9565294Z 	/home/runner/work/vitess/vitess/go/test/endtoend/cluster/topo_process.go:100 +0x61c
2022-03-26T12:40:17.9565546Z 
2022-03-26T12:40:17.9565686Z goroutine 55 [select, 10 minutes]:
2022-03-26T12:40:17.9566023Z net/http.(*persistConn).readLoop(0xc00037f680)
2022-03-26T12:40:17.9566459Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:2213 +0xda5
2022-03-26T12:40:17.9567098Z created by net/http.(*Transport).dialConn
2022-03-26T12:40:17.9567520Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:1750 +0x173e
2022-03-26T12:40:17.9567753Z 
2022-03-26T12:40:17.9567893Z goroutine 56 [select, 10 minutes]:
2022-03-26T12:40:17.9568234Z net/http.(*persistConn).writeLoop(0xc00037f680)
2022-03-26T12:40:17.9568658Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:2392 +0xf5
2022-03-26T12:40:17.9569043Z created by net/http.(*Transport).dialConn
2022-03-26T12:40:17.9569471Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:1751 +0x1791
2022-03-26T12:40:17.9569703Z 
2022-03-26T12:40:17.9569839Z goroutine 43 [select, 10 minutes]:
2022-03-26T12:40:17.9570155Z net/http.(*persistConn).readLoop(0xc00014c000)
2022-03-26T12:40:17.9570581Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:2213 +0xda5
2022-03-26T12:40:17.9570962Z created by net/http.(*Transport).dialConn
2022-03-26T12:40:17.9571368Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:1750 +0x173e
2022-03-26T12:40:17.9571606Z 
2022-03-26T12:40:17.9571744Z goroutine 44 [select, 10 minutes]:
2022-03-26T12:40:17.9572081Z net/http.(*persistConn).writeLoop(0xc00014c000)
2022-03-26T12:40:17.9572517Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:2392 +0xf5
2022-03-26T12:40:17.9572884Z created by net/http.(*Transport).dialConn
2022-03-26T12:40:17.9573308Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:1751 +0x1791
2022-03-26T12:40:17.9573542Z 
2022-03-26T12:40:17.9573681Z goroutine 64 [syscall, 10 minutes]:
2022-03-26T12:40:17.9574033Z syscall.Syscall6(0xf7, 0x1, 0x1bddf, 0xc00006de30, 0x1000004, 0x0, 0x0)
2022-03-26T12:40:17.9574473Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/syscall/asm_linux_amd64.s:43 +0x5
2022-03-26T12:40:17.9574873Z os.(*Process).blockUntilWaitable(0xc000046d50)
2022-03-26T12:40:17.9575294Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/wait_waitid.go:32 +0x9c
2022-03-26T12:40:17.9575627Z os.(*Process).wait(0xc000046d50)
2022-03-26T12:40:17.9576125Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/exec_unix.go:22 +0x28
2022-03-26T12:40:17.9576457Z os.(*Process).Wait(...)
2022-03-26T12:40:17.9576804Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/exec.go:132
2022-03-26T12:40:17.9577137Z os/exec.(*Cmd).Wait(0xc00021cf20)
2022-03-26T12:40:17.9577526Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/exec/exec.go:507 +0x54
2022-03-26T12:40:17.9577943Z vitess.io/vitess/go/test/endtoend/cluster.(*VtctldProcess).Setup.func1()
2022-03-26T12:40:17.9578451Z 	/home/runner/work/vitess/vitess/go/test/endtoend/cluster/vtctld_process.go:93 +0x29
2022-03-26T12:40:17.9578921Z created by vitess.io/vitess/go/test/endtoend/cluster.(*VtctldProcess).Setup
2022-03-26T12:40:17.9579428Z 	/home/runner/work/vitess/vitess/go/test/endtoend/cluster/vtctld_process.go:92 +0x82e
2022-03-26T12:40:17.9579680Z 
2022-03-26T12:40:17.9579804Z goroutine 60 [select, 10 minutes]:
2022-03-26T12:40:17.9580140Z net/http.(*persistConn).writeLoop(0xc00014c120)
2022-03-26T12:40:17.9580579Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:2392 +0xf5
2022-03-26T12:40:17.9580944Z created by net/http.(*Transport).dialConn
2022-03-26T12:40:17.9581366Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:1751 +0x1791
2022-03-26T12:40:17.9581597Z 
2022-03-26T12:40:17.9581733Z goroutine 76 [syscall, 10 minutes]:
2022-03-26T12:40:17.9582096Z syscall.Syscall6(0xf7, 0x1, 0x1c039, 0xc00046c630, 0x1000004, 0x0, 0x0)
2022-03-26T12:40:17.9582519Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/syscall/asm_linux_amd64.s:43 +0x5
2022-03-26T12:40:17.9582913Z os.(*Process).blockUntilWaitable(0xc000160450)
2022-03-26T12:40:17.9583340Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/wait_waitid.go:32 +0x9c
2022-03-26T12:40:17.9583669Z os.(*Process).wait(0xc000160450)
2022-03-26T12:40:17.9584419Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/exec_unix.go:22 +0x28
2022-03-26T12:40:17.9584767Z os.(*Process).Wait(...)
2022-03-26T12:40:17.9585307Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/exec.go:132
2022-03-26T12:40:17.9585730Z os/exec.(*Cmd).Wait(0xc0001549a0)
2022-03-26T12:40:17.9586122Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/os/exec/exec.go:507 +0x54
2022-03-26T12:40:17.9586557Z vitess.io/vitess/go/test/endtoend/cluster.(*VttabletProcess).Setup.func1()
2022-03-26T12:40:17.9587059Z 	/home/runner/work/vitess/vitess/go/test/endtoend/cluster/vttablet_process.go:144 +0x2f
2022-03-26T12:40:17.9587548Z created by vitess.io/vitess/go/test/endtoend/cluster.(*VttabletProcess).Setup
2022-03-26T12:40:17.9588065Z 	/home/runner/work/vitess/vitess/go/test/endtoend/cluster/vttablet_process.go:142 +0xcd8
2022-03-26T12:40:17.9588327Z 
2022-03-26T12:40:17.9588465Z goroutine 71 [select, 10 minutes]:
2022-03-26T12:40:17.9588791Z net/http.(*persistConn).readLoop(0xc00037e360)
2022-03-26T12:40:17.9589227Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:2213 +0xda5
2022-03-26T12:40:17.9589609Z created by net/http.(*Transport).dialConn
2022-03-26T12:40:17.9590020Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:1750 +0x173e
2022-03-26T12:40:17.9590259Z 
2022-03-26T12:40:17.9590394Z goroutine 72 [select, 10 minutes]:
2022-03-26T12:40:17.9590727Z net/http.(*persistConn).writeLoop(0xc00037e360)
2022-03-26T12:40:17.9591160Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:2392 +0xf5
2022-03-26T12:40:17.9591521Z created by net/http.(*Transport).dialConn
2022-03-26T12:40:17.9591941Z 	/opt/hostedtoolcache/go/1.18.0/x64/src/net/http/transport.go:1751 +0x1791
2022-03-26T12:40:17.9592173Z 
2022-03-26T12:40:17.9592271Z rax    0xca
2022-03-26T12:40:17.9592487Z rbx    0x0
2022-03-26T12:40:17.9592717Z rcx    0x46d063
2022-03-26T12:40:17.9593151Z rdx    0x0
2022-03-26T12:40:17.9593379Z rdi    0x1f53f88
2022-03-26T12:40:17.9593611Z rsi    0x80
2022-03-26T12:40:17.9593877Z rbp    0x7ffd8ccef900
2022-03-26T12:40:17.9594125Z rsp    0x7ffd8ccef8b8
2022-03-26T12:40:17.9594366Z r8     0x0
2022-03-26T12:40:17.9594584Z r9     0x0
2022-03-26T12:40:17.9594785Z r10    0x0
2022-03-26T12:40:17.9595017Z r11    0x286
2022-03-26T12:40:17.9595352Z r12    0xc000058000
2022-03-26T12:40:17.9595569Z r13    0x1
2022-03-26T12:40:17.9595800Z r14    0x1f538a0
2022-03-26T12:40:17.9596045Z r15    0x7fcffe4232a0
2022-03-26T12:40:17.9596287Z rip    0x46d061
2022-03-26T12:40:17.9596522Z rflags 0x286
2022-03-26T12:40:17.9596752Z cs     0x33
2022-03-26T12:40:17.9596980Z fs     0x0
2022-03-26T12:40:17.9597186Z gs     0x0
2022-03-26T12:40:17.9597491Z *** Test killed with quit: ran too long (11m0s).
2022-03-26T12:40:17.9597914Z FAIL	vitess.io/vitess/go/test/endtoend/vtgate/schematracker/unsharded	660.008s
2022-03-26T12:40:17.9616298Z FAIL
```
```

**Comment by deepthi** [comment]
@vitessio/query-serving

**Comment by systay** [comment]
I don't mean to get into semantics here, but didn't this just time out? In my mental model, that is different from a flaky test

**Comment by frouioui** [comment]
This seems to be a timeout indeed. Let's fill this thread with some links to flaky query-serving upgrade-downgrade CI tests to have more context on why they timeout.
